var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,k="undefined"!=typeof WorkerGlobalScope,p="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,r=k&&self.name?.startsWith("em-pthread");if(p){var ba=require("worker_threads");global.Worker=ba.Worker;r=(k=!ba.gf)&&"em-pthread"==ba.workerData}
var ca=Object.assign({},h),da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;p?ha=__filename:k&&(ha=self.location.href);var t="",ia,ja;
if(p){var fs=require("fs"),ka=require("path");t=__dirname+"/";ja=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a)};ia=a=>{a=la(a)?new URL(a):ka.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!h.thisProgram&&1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||k)k?t=self.location.href:"undefined"!=typeof document&&
document.currentScript&&(t=document.currentScript.src),t=t.startsWith("blob:")?"":t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1),p||(k&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=a=>la(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url))));var ma=console.log.bind(console),na=console.error.bind(console);p&&(ma=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),na=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var oa=h.print||ma,u=h.printErr||na;Object.assign(h,ca);ca=null;h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);var pa=h.wasmBinary,qa,ra,sa=!1,ta,w,x,ua,va,y,z,xa,A;
function ya(){var a=qa.buffer;h.HEAP8=w=new Int8Array(a);h.HEAP16=ua=new Int16Array(a);h.HEAPU8=x=new Uint8Array(a);h.HEAPU16=va=new Uint16Array(a);h.HEAP32=y=new Int32Array(a);h.HEAPU32=z=new Uint32Array(a);h.HEAPF32=xa=new Float32Array(a);h.HEAPF64=A=new Float64Array(a)}
if(r){var za;if(p){var Aa=ba.parentPort;Aa.on("message",c=>onmessage({data:c}));Object.assign(globalThis,{self:global,postMessage:c=>Aa.postMessage(c)})}var Ba=!1;function a(...c){c=c.join(" ");p?fs.writeSync(2,c+"\n"):console.error(c)}h.printErr||(u=a);self.alert=function(...c){postMessage({Tc:"alert",text:c.join(" "),He:Ca()})};self.onunhandledrejection=c=>{throw c.reason||c;};function b(c){try{var d=c.data,e=d.Tc;if("load"===e){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({Tc:"loaded"});
for(let g of f)b(g);self.onmessage=b};for(const g of d.te)if(!h[g]||h[g].proxy)h[g]=(...l)=>{postMessage({Tc:"callHandler",se:g,args:l})},"print"==g&&(oa=h[g]),"printErr"==g&&(u=h[g]);qa=d.Ke;ya();za(d.Le)}else if("run"===e){Da(d.Sc);Ea(d.Sc,0,0,1,0,0);Fa();Ga(d.Sc);Ba||=!0;try{Ha(d.Fe,d.nd)}catch(f){if("unwind"!=f)throw f;}}else"setimmediate"!==d.target&&("checkMailbox"===e?Ba&&Ia():e&&(u(`worker: received unknown command ${e}`),u(d)))}catch(f){throw Ja(),f;}}self.onmessage=b}
if(!r){if(h.wasmMemory)qa=h.wasmMemory;else{var Ka=h.INITIAL_MEMORY||536870912;qa=new WebAssembly.Memory({initial:Ka/65536,maximum:Ka/65536,shared:!0})}ya()}var La=[],Ma=[],Oa=[],Pa=[];
function Qa(){if(!r){if(!h.noFSInit&&!Ra){var a,b,c;Ra=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?C("/dev","stdin",a):Sa("/dev/tty","/dev/stdin");b?C("/dev","stdout",null,b):Sa("/dev/tty","/dev/stdout");c?C("/dev","stderr",null,c):Sa("/dev/tty1","/dev/stderr");Ta("/dev/stdin",0);Ta("/dev/stdout",1);Ta("/dev/stderr",1)}Ua=!1;Va(Ma)}}var Wa=0,Xa=null,Ya=null;function Za(){Wa++;h.monitorRunDependencies?.(Wa)}
function $a(){Wa--;h.monitorRunDependencies?.(Wa);if(0==Wa&&(null!==Xa&&(clearInterval(Xa),Xa=null),Ya)){var a=Ya;Ya=null;a()}}function ab(a){h.onAbort?.(a);a="Aborted("+a+")";u(a);sa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var bb=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),cb;function db(a){if(a==cb&&pa)return new Uint8Array(pa);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}
function eb(a){return pa?Promise.resolve().then(()=>db(a)):ia(a).then(b=>new Uint8Array(b),()=>db(a))}function fb(a,b,c){return eb(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{u(`failed to asynchronously prepare wasm: ${d}`);ab(d)})}
function gb(a,b){var c=cb;pa||"function"!=typeof WebAssembly.instantiateStreaming||bb(c)||la(c)||p||"function"!=typeof fetch?fb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){u(`wasm streaming compile failed: ${e}`);u("falling back to ArrayBuffer instantiation");return fb(c,a,b)}))}
function hb(){ib={ib:jb,ob:kb,rb:lb,na:mb,wb:nb,xb:ob,Ab:pb,Bb:qb,ub:rb,nb:sb,sb:tb,qb:ub,ia:vb,tb:Ga,zb:wb,jb:xb,Mb:yb,ja:zb,yb:Ab,T:Bb,da:Cb,m:Db,Nb:Eb,cb:Fb,mb:Gb,Y:Hb,P:Ib,Z:Jb,ha:Kb,fa:Lb,ga:Mb,db:Nb,za:Ob,qa:Pb,pa:Qb,ta:Rb,ua:Sb,$:Tb,_:Ub,X:Vb,aa:Wb,ba:Xb,ca:Yb,ea:Zb,W:$b,V:ac,ma:bc,Pa:cc,Ca:dc,Ha:ec,kb:fc,lb:gc,ic:hc,ka:ic,vb:jc,hb:kc,la:lc,l:mc,M:nc,c:oc,b:pc,j:qc,Ua:rc,k:sc,d:tc,U:uc,ya:vc,z:wc,A:xc,Rb:yc,Wa:zc,O:Ac,H:Bc,Ba:Cc,E:Dc,Aa:Ec,o:Fc,Db:Gc,Ma:Hc,Oa:Ic,Ia:Jc,Fb:Kc,xa:Lc,Gb:Mc,g:Nc,
w:Oc,R:Pc,Q:Qc,v:Rc,S:Sc,Ya:Tc,s:Uc,t:Vc,f:Wc,va:Xc,Tb:Yc,Ub:Zc,G:$c,Wb:ad,Vb:bd,i:cd,ec:dd,I:ed,n:fd,u:gd,wa:hd,Xa:jd,J:kd,Va:ld,Ja:md,Sa:nd,_a:od,Ea:pd,e:qd,Fa:rd,L:sd,Cb:td,oa:ud,$a:vd,q:wd,Qb:xd,Ga:yd,Za:zd,D:Ad,Sb:Bd,Ta:Cd,N:Dd,h:Ed,Da:Fd,Eb:Gd,Ib:Hd,C:Id,r:Jd,Hb:Kd,B:Ld,La:Md,Na:Nd,Ra:Od,Ka:Pd,Qa:Qd,Ob:Rd,Pb:Sd,dc:Td,K:Ud,$b:Vd,cc:Wd,_b:Xd,bc:Yd,Zb:Zd,ac:$d,Yb:ae,Xb:be,p:ce,fc:de,gc:ee,F:fe,a:qa,pb:ge,gb:he,fb:ie,eb:je,bb:ke,hc:le,Lb:me,Kb:ne,Jb:oe,x:pe,ab:qe,y:re,sa:se,ra:te};return{a:ib}}
var ue,ve;function he(){h.ce=a=>{0!=we()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.ce)}function me(){window.removeEventListener("beforeunload",h.ce)}function ie(){h.he=a=>{const b=a.clipboardData.getData("text");xe(()=>{const c=ye(b);ze(c)})};window.addEventListener("paste",h.he)}function ne(){window.removeEventListener("paste",h.he)}
function je(a){h.uf=[];a=a?E(x,a):"";a=document.getElementById(a);h.de=b=>{b.stopPropagation();b.preventDefault()};h.ee=b=>{b.stopPropagation();b.preventDefault()};h.fe=b=>{b.stopPropagation();b.preventDefault()};h.ge=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.vf=c;Ae(c.length);for(let e=0;e<c.length;e++)xe(()=>{const f=ye(c[e].name);Be(e,f)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ce(b.clientX,b.clientY,d)};a.addEventListener("dragenter",
h.de,!1);a.addEventListener("dragleave",h.ee,!1);a.addEventListener("dragover",h.fe,!1);a.addEventListener("drop",h.ge,!1)}function oe(a){a=a?E(x,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",h.de);a.removeEventListener("dragleave",h.ee);a.removeEventListener("dragover",h.fe);a.removeEventListener("drop",h.ge)}
function le(a){a=a?E(x,a):"";h.ld=document.getElementById(a);h.ld||console.log("sokol_app.h: invalid target:"+a);h.ld.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)}function pe(){h.ld&&h.ld.requestPointerLock&&h.ld.requestPointerLock()}function ke(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)}
function qe(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(x.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)}
function se(a,b){b=b?E(x,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");De(a,d)}else Ee(a,c.status)};c.send()}
function re(a,b,c,d,e,f){b=b?E(x,b):"";const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const l=0<d;l&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!l){const m=new Uint8Array(g.response),n=m.length;n<=f?(x.set(m,e),Fe(a,d,n)):Ge(a)}else Ee(a,g.status)};g.send()}
function te(a,b){b=b?E(x,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}class He{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ie=a=>{a.terminate();a.onmessage=()=>{}},Oe=a=>{0==Je.length&&(Ke(),Le(Je[0]));var b=Je.pop();if(!b)return 6;Me.push(b);Ne[a.Sc]=b;b.Sc=a.Sc;var c={Tc:"run",Fe:a.Ee,nd:a.nd,Sc:a.Sc};p&&b.unref();b.postMessage(c,a.ie);return 0},Pe=0,H=(a,b,...c)=>{for(var d=c.length,e=Qe(),f=Re(8*d),g=f>>3,l=0;l<c.length;l++)A[g+l]=c[l];a=Se(a,0,d,f,b);Te(e);return a};
function ge(a){if(r)return H(0,1,a);ta=a;if(!(Ue||0<Pe)){for(var b of Me)Ie(b);for(b of Je)Ie(b);Je=[];Me=[];Ne={};h.onExit?.(a);sa=!0}fa(a,new He(a))}var Ve=a=>{a instanceof He||"unwind"==a||fa(1,a)};function We(a){if(r)return H(1,0,a);hc(a)}var hc=a=>{ta=a;if(r)throw We(a),"unwind";ge(a)},Je=[],Me=[],Xe=[],Ne={};function Ye(){for(var a=4;a--;)Ke();La.unshift(()=>{Za("loading-workers");Ze(()=>$a("loading-workers"))})}
var af=a=>{var b=a.Sc;delete Ne[b];Je.push(a);Me.splice(Me.indexOf(a),1);a.Sc=0;$e(b)};function Fa(){Xe.forEach(a=>a())}
var Le=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.Tc;if(f.td&&f.td!=Ca()){var l=Ne[f.td];l?l.postMessage(f,f.ie):u(`Internal error! Worker sent a message "${g}" to target pthread ${f.td}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ia();else if("spawnThread"===g)Oe(f);else if("cleanupThread"===g)af(Ne[f.Ge]);else if("loaded"===g)a.loaded=!0,p&&!a.Sc&&a.unref(),b(a);else if("alert"===g)alert(`Thread ${f.He}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);
else if("callHandler"===g)h[f.se](...f.args);else g&&u(`worker sent an unknown command ${g}`)};a.onerror=f=>{u(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};p&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({Tc:"load",te:c,Ke:qa,Le:ra})});function Ze(a){r?a():Promise.all(Je.map(Le)).then(a)}
function Ke(){var a=ha;h.mainScriptUrlOrBlob&&(a=h.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{workerData:"em-pthread",name:"em-pthread"});Je.push(a)}
var bf,Va=a=>{for(;0<a.length;)a.shift()(h)},Da=a=>{var b=z[a+52>>2];cf(b,b-z[a+56>>2]);Te(b)},I,Ha=(a,b)=>{Ue=Pe=0;a=I.get(a)(b);Ue||0<Pe?ta=a:df(a)},Ue=h.noExitRuntime||!0,ef="undefined"!=typeof TextDecoder?new TextDecoder:void 0,E=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ef)return ef.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=
a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},jb=(a,b,c,d)=>ab(`Assertion failed: ${a?E(x,a):""}, at: `+[b?b?E(x,b):"":"unknown filename",c,d?d?E(x,d):"":"unknown function"]),kb=(a,b)=>I.get(a)(b);function ff(a,b,c,d){return r?H(2,1,a,b,c,d):lb(a,b,c,d)}
var lb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return ff(a,b,c,d);a={Ee:c,Sc:a,nd:d,ie:e};return r?(a.Tc="spawnThread",postMessage(a,e),0):Oe(a)},hf=()=>{var a=y[+gf>>2];gf+=4;return a},jf=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},kf=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=jf(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},lf=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},mf=a=>{if("/"===a)return"/";a=kf(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},nf=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>(c.set(crypto.getRandomValues(new Uint8Array(c.byteLength))),c);if(p)try{var a=require("crypto");
if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}ab("initRandomDevice")},of=a=>(of=nf())(a),pf=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=jf(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},qf=[],rf=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);
127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},J=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};
function sf(a){var b=Array(rf(a)+1);a=J(a,b,0,b.length);b.length=a;return b}var tf=[];function uf(a,b){tf[a]={input:[],output:[],Zc:b};vf(a,wf)}
var wf={open(a){var b=tf[a.node.rdev];if(!b)throw new K(43);a.tty=b;a.seekable=!1},close(a){a.tty.Zc.fsync(a.tty)},fsync(a){a.tty.Zc.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Zc.Wd)throw new K(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Zc.Wd(a.tty)}catch(l){throw new K(29);}if(void 0===g&&0===e)throw new K(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Zc.Dd)throw new K(60);try{for(var e=0;e<d;e++)a.tty.Zc.Dd(a.tty,b[c+
e])}catch(f){throw new K(29);}d&&(a.node.timestamp=Date.now());return e}},xf={Wd(){a:{if(!qf.length){var a=null;if(p){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}qf=sf(a)}a=qf.shift()}return a},Dd(a,b){null===b||10===b?(oa(E(a.output)),
a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(E(a.output)),a.output=[])},we(){return{Re:25856,Te:5,Qe:191,Se:35387,Pe:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},xe(){return 0},ye(){return[24,80]}},yf={Dd(a,b){null===b||10===b?(u(E(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(u(E(a.output)),a.output=[])}};
function zf(a,b){var c=a.kc?a.kc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.kc,a.kc=new Uint8Array(b),0<a.Nc&&a.kc.set(c.subarray(0,a.Nc),0))}
var L={Uc:null,Yc(){return L.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);L.Uc||(L.Uc={dir:{node:{cd:L.Lc.cd,Qc:L.Lc.Qc,lookup:L.Lc.lookup,rd:L.Lc.rd,rename:L.Lc.rename,unlink:L.Lc.unlink,rmdir:L.Lc.rmdir,readdir:L.Lc.readdir,symlink:L.Lc.symlink},stream:{dd:L.Mc.dd}},file:{node:{cd:L.Lc.cd,Qc:L.Lc.Qc},stream:{dd:L.Mc.dd,read:L.Mc.read,write:L.Mc.write,Nd:L.Mc.Nd,Bd:L.Mc.Bd,$d:L.Mc.$d}},link:{node:{cd:L.Lc.cd,Qc:L.Lc.Qc,readlink:L.Lc.readlink},
stream:{}},Pd:{node:{cd:L.Lc.cd,Qc:L.Lc.Qc},stream:Af}});c=Bf(a,b,c,d);M(c.mode)?(c.Lc=L.Uc.dir.node,c.Mc=L.Uc.dir.stream,c.kc={}):32768===(c.mode&61440)?(c.Lc=L.Uc.file.node,c.Mc=L.Uc.file.stream,c.Nc=0,c.kc=null):40960===(c.mode&61440)?(c.Lc=L.Uc.link.node,c.Mc=L.Uc.link.stream):8192===(c.mode&61440)&&(c.Lc=L.Uc.Pd.node,c.Mc=L.Uc.Pd.stream);c.timestamp=Date.now();a&&(a.kc[b]=c,a.timestamp=c.timestamp);return c},ef(a){return a.kc?a.kc.subarray?a.kc.subarray(0,a.Nc):new Uint8Array(a.kc):new Uint8Array(0)},
Lc:{cd(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;M(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Nc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.me=4096;b.blocks=Math.ceil(b.size/b.me);return b},Qc(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Nc!=b))if(0==
b)a.kc=null,a.Nc=0;else{var c=a.kc;a.kc=new Uint8Array(b);c&&a.kc.set(c.subarray(0,Math.min(b,a.Nc)));a.Nc=b}},lookup(){throw L.Sd;},rd(a,b,c,d){return L.createNode(a,b,c,d)},rename(a,b,c){if(M(a.mode)){try{var d=Cf(b,c)}catch(f){}if(d)for(var e in d.kc)throw new K(55);}delete a.parent.kc[a.name];a.parent.timestamp=Date.now();a.name=c;b.kc[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.kc[b];a.timestamp=Date.now()},rmdir(a,b){var c=Cf(a,b),d;for(d in c.kc)throw new K(55);delete a.kc[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.kc))b.push(c);return b},symlink(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new K(28);return a.link}},Mc:{read(a,b,c,d,e){var f=a.node.kc;if(e>=a.node.Nc)return 0;a=Math.min(a.node.Nc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.kc||a.kc.subarray)){if(f)return a.kc=
b.subarray(c,c+d),a.Nc=d;if(0===a.Nc&&0===e)return a.kc=b.slice(c,c+d),a.Nc=d;if(e+d<=a.Nc)return a.kc.set(b.subarray(c,c+d),e),d}zf(a,e+d);if(a.kc.subarray&&b.subarray)a.kc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.kc[e+f]=b[c+f];a.Nc=Math.max(a.Nc,e+d);return d},dd(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Nc);if(0>b)throw new K(28);return b},Nd(a,b,c){zf(a.node,b+c);a.node.Nc=Math.max(a.node.Nc,b+c)},Bd(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new K(43);
a=a.node.kc;if(e&2||!a||a.buffer!==w.buffer){d=!0;ab();e=void 0;if(!e)throw new K(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);w.set(a,e)}}else d=!1,e=a.byteOffset;return{pf:e,Ne:d}},$d(a,b,c,d){L.Mc.write(a,b,0,d,c,!1);return 0}}},Df=(a,b,c)=>{var d=`al ${a}`;ia(a).then(e=>{b(new Uint8Array(e));d&&$a(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Za(d)},Ef=h.preloadPlugins||[],Ff=(a,b,c,d)=>{"undefined"!=typeof Browser&&
Browser.ff();var e=!1;Ef.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Hf=(a,b,c,d,e,f,g,l,m,n)=>{function q(B){function F(G){n?.();l||Gf(a,b,G,d,e,m);f?.();$a(D)}Ff(B,v,F,()=>{g?.();$a(D)})||F(B)}var v=b?pf(kf(a+"/"+b)):a,D=`cp ${v}`;Za(D);"string"==typeof c?Df(c,q,g):q(c)},If=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Jf=null,Kf={},Lf=[],Mf=1,Nf=null,Ra=!1,Ua=!0,K=class{name="ErrnoError";constructor(a){this.bd=a}},Of={},Pf=class{Oc={};node=null;get flags(){return this.Oc.flags}set flags(a){this.Oc.flags=
a}get position(){return this.Oc.position}set position(a){this.Oc.position=a}},Qf=class{Lc={};Mc={};kd=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Yc=a.Yc;this.id=Mf++;this.name=b;this.mode=c;this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Ae(){return M(this.mode)}get ze(){return 8192===(this.mode&61440)}};
function Rf(a,b={}){a=pf(a);if(!a)return{path:"",node:null};b=Object.assign({Vd:!0,Ed:0},b);if(8<b.Ed)throw new K(32);a=a.split("/").filter(g=>!!g);for(var c=Jf,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Cf(c,a[e]);d=kf(d+"/"+a[e]);c.kd&&(!f||f&&b.Vd)&&(c=c.kd.root);if(!f||b.xd)for(f=0;40960===(c.mode&61440);)if(c=Sf(d),d=pf(lf(d),c),c=Rf(d,{Ed:b.Ed+1}).node,40<f++)throw new K(32);}return{path:d,node:c}}
function Tf(a){for(var b;;){if(a===a.parent)return a=a.Yc.Zd,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Uf(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Nf.length}function Cf(a,b){var c=M(a.mode)?(c=Vf(a,"x"))?c:a.Lc.lookup?0:2:54;if(c)throw new K(c);for(c=Nf[Uf(a.id,b)];c;c=c.jd){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Lc.lookup(a,b)}
function Bf(a,b,c,d){a=new Qf(a,b,c,d);b=Uf(a.parent.id,a.name);a.jd=Nf[b];return Nf[b]=a}function M(a){return 16384===(a&61440)}function Wf(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Vf(a,b){if(Ua)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Xf(a,b){try{return Cf(a,b),20}catch(c){}return Vf(a,"wx")}function Yf(a){a=Lf[a];if(!a)throw new K(8);return a}
function Zf(a,b=-1){a=Object.assign(new Pf,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Lf[b])break a;throw new K(33);}a.fd=b;return Lf[b]=a}function $f(a,b=-1){a=Zf(a,b);a.Mc?.$e?.(a);return a}var Af={open(a){a.Mc=Kf[a.node.rdev].Mc;a.Mc.open?.(a)},dd(){throw new K(70);}};function vf(a,b){Kf[a]={Mc:b}}
function ag(a,b){var c="/"===b;if(c&&Jf)throw new K(10);if(!c&&b){var d=Rf(b,{Vd:!1});b=d.path;d=d.node;if(d.kd)throw new K(10);if(!M(d.mode))throw new K(54);}b={type:a,lf:{},Zd:b,Ce:[]};a=a.Yc(b);a.Yc=b;b.root=a;c?Jf=a:d&&(d.kd=b,d.Yc&&d.Yc.Ce.push(b))}function bg(a,b,c){var d=Rf(a,{parent:!0}).node;a=mf(a);if(!a||"."===a||".."===a)throw new K(28);var e=Xf(d,a);if(e)throw new K(e);if(!d.Lc.rd)throw new K(63);return d.Lc.rd(d,a,b,c)}function cg(a,b=438){return bg(a,b&4095|32768,0)}
function O(a){return bg(a,16895,0)}function dg(a,b,c){"undefined"==typeof c&&(c=b,b=438);return bg(a,b|8192,c)}function Sa(a,b){if(!pf(a))throw new K(44);var c=Rf(b,{parent:!0}).node;if(!c)throw new K(44);b=mf(b);var d=Xf(c,b);if(d)throw new K(d);if(!c.Lc.symlink)throw new K(63);c.Lc.symlink(c,b,a)}
function eg(a){var b=Rf(a,{parent:!0}).node;if(!b)throw new K(44);var c=mf(a);a=Cf(b,c);a:{try{var d=Cf(b,c)}catch(f){d=f.bd;break a}var e=Vf(b,"wx");d=e?e:M(d.mode)?31:0}if(d)throw new K(d);if(!b.Lc.unlink)throw new K(63);if(a.kd)throw new K(10);b.Lc.unlink(b,c);b=Uf(a.parent.id,a.name);if(Nf[b]===a)Nf[b]=a.jd;else for(b=Nf[b];b;){if(b.jd===a){b.jd=a.jd;break}b=b.jd}}function Sf(a){a=Rf(a).node;if(!a)throw new K(44);if(!a.Lc.readlink)throw new K(28);return a.Lc.readlink(a)}
function fg(a,b){a="string"==typeof a?Rf(a,{xd:!0}).node:a;if(!a.Lc.Qc)throw new K(63);a.Lc.Qc(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ta(a,b,c=438){if(""===a)throw new K(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)var e=a;else{a=kf(a);try{e=Rf(a,{xd:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new K(20);}else e=bg(a,c,0),d=!0;if(!e)throw new K(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!M(e.mode))throw new K(54);if(!d&&(c=e?40960===(e.mode&61440)?
32:M(e.mode)&&("r"!==Wf(b)||b&512)?31:Vf(e,Wf(b)):44))throw new K(c);if(b&512&&!d){c=e;c="string"==typeof c?Rf(c,{xd:!0}).node:c;if(!c.Lc.Qc)throw new K(63);if(M(c.mode))throw new K(31);if(32768!==(c.mode&61440))throw new K(28);if(d=Vf(c,"w"))throw new K(d);c.Lc.Qc(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Zf({node:e,path:Tf(e),flags:b,seekable:!0,position:0,Mc:e.Mc,Ie:[],error:!1});e.Mc.open&&e.Mc.open(e);!h.logReadFiles||b&1||a in Of||(Of[a]=1);return e}
function gg(a){if(null===a.fd)throw new K(8);a.yd&&(a.yd=null);try{a.Mc.close&&a.Mc.close(a)}catch(b){throw b;}finally{Lf[a.fd]=null}a.fd=null}function hg(a,b,c){if(null===a.fd)throw new K(8);if(!a.seekable||!a.Mc.dd)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.Mc.dd(a,b,c);a.Ie=[]}
function ig(a,b,c,d,e,f){if(0>d||0>e)throw new K(28);if(null===a.fd)throw new K(8);if(0===(a.flags&2097155))throw new K(8);if(M(a.node.mode))throw new K(31);if(!a.Mc.write)throw new K(28);a.seekable&&a.flags&1024&&hg(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new K(70);b=a.Mc.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function jg(a,b){a="string"==typeof a?a:Tf(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=kf(a+"/"+c);try{O(d)}catch(e){}a=d}}return d}function kg(a,b,c,d){a=kf(("string"==typeof a?a:Tf(a))+"/"+b);return cg(a,If(c,d))}
function Gf(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Tf(a),g=b?kf(a+"/"+b):a);a=If(d,e);g=cg(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}fg(g,a|146);b=Ta(g,577);ig(b,c,0,c.length,0,f);gg(b);fg(g,a)}}
function C(a,b,c,d){a=kf(("string"==typeof a?a:Tf(a))+"/"+b);b=If(!!c,!!d);C.Yd??(C.Yd=64);var e=C.Yd++<<8|0;vf(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,m){for(var n=0,q=0;q<m;q++){try{var v=c()}catch(D){throw new K(29);}if(void 0===v&&0===n)throw new K(6);if(null===v||void 0===v)break;n++;g[l+q]=v}n&&(f.node.timestamp=Date.now());return n},write(f,g,l,m){for(var n=0;n<m;n++)try{d(g[l+n])}catch(q){throw new K(29);}m&&(f.node.timestamp=Date.now());return n}});return dg(a,
b,e)}function lg(a){if(!(a.ze||a.Ae||a.link||a.kc)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.kc=ja(a.url),a.Nc=a.kc.length}catch(b){throw new K(29);}}}
function mg(a,b,c,d,e){class f{hd=!1;Oc=[];gd=void 0;Ld=0;Kd=0;get(q){if(!(q>this.length-1||0>q)){var v=q%this.chunkSize;return this.gd(q/this.chunkSize|0)[v]}}le(q){this.gd=q}Md(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var v=Number(q.getResponseHeader("Content-length")),D,B=(D=q.getResponseHeader("Accept-Ranges"))&&"bytes"===D;q=(D=q.getResponseHeader("Content-Encoding"))&&"gzip"===
D;var F=1048576;B||(F=v);var G=this;G.le(V=>{var Na=V*F,wa=(V+1)*F-1;wa=Math.min(wa,v-1);if("undefined"==typeof G.Oc[V]){var Fh=G.Oc;if(Na>wa)throw Error("invalid range ("+Na+", "+wa+") or no bytes requested!");if(wa>v-1)throw Error("only "+v+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);v!==F&&N.setRequestHeader("Range","bytes="+Na+"-"+wa);N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);if(!(200<=
N.status&&300>N.status||304===N.status))throw Error("Couldn't load "+c+". Status: "+N.status);Na=void 0!==N.response?new Uint8Array(N.response||[]):sf(N.responseText||"");Fh[V]=Na}if("undefined"==typeof G.Oc[V])throw Error("doXHR failed!");return G.Oc[V]});if(q||!v)F=v=1,F=v=this.gd(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ld=v;this.Kd=F;this.hd=!0}get length(){this.hd||this.Md();return this.Ld}get chunkSize(){this.hd||this.Md();return this.Kd}}
if("undefined"!=typeof XMLHttpRequest){if(!k)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;var l=void 0}else l=c,g=void 0;var m=kg(a,b,d,e);g?m.kc=g:l&&(m.kc=null,m.url=l);Object.defineProperties(m,{Nc:{get:function(){return this.kc.length}}});var n={};Object.keys(m.Mc).forEach(q=>{var v=m.Mc[q];n[q]=(...D)=>{lg(m);return v(...D)}});n.read=(q,v,D,B,F)=>{lg(m);q=q.node.kc;if(F>=q.length)v=0;else{B=Math.min(q.length-
F,B);if(q.slice)for(var G=0;G<B;G++)v[D+G]=q[F+G];else for(G=0;G<B;G++)v[D+G]=q.get(F+G);v=B}return v};n.Bd=()=>{lg(m);ab();throw new K(48);};m.Mc=n;return m}var ng={},gf=void 0;
function mb(a,b,c){if(r)return H(3,1,a,b,c);gf=c;try{var d=Yf(a);switch(b){case 0:var e=hf();if(0>e)break;for(;Lf[e];)e++;return $f(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=hf(),d.flags|=e,0;case 12:return e=hf(),ua[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof ng||"ErrnoError"!==f.name)throw f;return-f.bd}}
function nb(a,b,c){if(r)return H(4,1,a,b,c);gf=c;try{var d=Yf(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Zc.we){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=hf();y[e>>2]=25856;y[e+4>>2]=5;y[e+8>>2]=191;y[e+12>>2]=35387;for(var f=0;32>f;f++)w[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Zc.xe)for(e=hf(),a=[],f=0;32>f;f++)a.push(w[e+
f+17]);return 0;case 21519:if(!d.tty)return-59;e=hf();return y[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=hf();if(!d.Mc.ve)throw new K(59);return d.Mc.ve(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Zc.ye&&(f=[24,80],e=hf(),ua[e>>1]=f[0],ua[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof ng||"ErrnoError"!==g.name)throw g;return-g.bd}}
function ob(a,b,c,d){if(r)return H(5,1,a,b,c,d);gf=d;try{b=b?E(x,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Yf(a).path;if(0==e.length)throw new K(44);b=kf(f+"/"+e)}var g=d?hf():0;return Ta(b,c,g).fd}catch(l){if("undefined"==typeof ng||"ErrnoError"!==l.name)throw l;return-l.bd}}
var pb=()=>ab(""),qb=a=>{do{var b=z[a>>2];a+=4;var c=z[a>>2];a+=4;var d=z[a>>2];a+=4;b=b?E(x,b):"";jg("/",lf(b),!0,!0);Gf(b,null,w.subarray(d,d+c),!0,!0,!0)}while(z[a>>2])},rb=a=>{Ea(a,!k,1,!aa,1048576,!1);Fa()},og=()=>{if(!(Ue||0<Pe))try{r?df(ta):hc(ta)}catch(a){Ve(a)}},Ga=a=>{"function"===typeof Atomics.Je&&(Atomics.Je(y,a>>2,a).value.then(Ia),Atomics.store(y,a+128>>2,1))},Ia=()=>{var a=Ca();if(a&&(Ga(a),!sa))try{pg(),og()}catch(b){Ve(b)}},sb=(a,b)=>{a==b?setTimeout(Ia):r?postMessage({td:a,Tc:"checkMailbox"}):
(a=Ne[a])&&a.postMessage({Tc:"checkMailbox"})},qg=[],tb=(a,b,c,d,e)=>{qg.length=d;b=e>>3;for(e=0;e<d;e++)qg[e]=A[b+e];a=rg[a];bf=c;c=a(...qg);bf=0;return c},ub=()=>{Ue=!1;Pe=0},vb=a=>{r?postMessage({Tc:"cleanupThread",Ge:a}):af(Ne[a])},wb=a=>{p&&Ne[a].ref()},xb=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();z[a>>2]=60*Math.max(f,e);y[b>>2]=Number(f!=e);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/
60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(J(a,x,c,17),J(b,x,d,17)):(J(a,x,d,17),J(b,x,c,17))},Bg=(a,b)=>{sg=a;tg=b;if(ug)if(vg||(Pe+=1,vg=!0),0==a)wg=function(){setTimeout(xg,Math.max(0,yg+b-(performance.timeOrigin+performance.now()))|0)};else if(1==a)wg=function(){zg(xg)};else if(2==a){if("undefined"==typeof Ag)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),
c.shift()()},!0);Ag=d=>{c.push(d);if(k){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ag=setImmediate;wg=function(){Ag(xg)}}},Db=()=>performance.timeOrigin+performance.now(),Kg=(a,b,c,d,e)=>{function f(){return g<Cg?(--Pe,og(),!1):!0}ug=a;Dg=d;var g=Cg;vg=!1;xg=function(){if(!sa)if(0<Eg.length){var l=Eg.shift();l.cf(l.nd);if(Fg){var m=Fg,n=0==m%1?m-1:Math.floor(m);Fg=l.Ve?n:(8*m+(n+.5))/9}h.setStatus&&
(l=h.statusMessage||"Please wait...",m=Fg??0,n=Gg.af??0,m?m<n?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(xg,0)}else if(f())if(Hg=Hg+1|0,1==sg&&1<tg&&0!=Hg%tg)wg();else{0==sg&&(yg=performance.timeOrigin+performance.now());a:if(!sa){for(l of Ig)if(!1===l())break a;if(!sa)try{a(),og()}catch(q){Ve(q)}for(m of Jg)m()}f()&&wg()}};e||(b&&0<b?Bg(0,1E3/b):Bg(1,1),wg());if(c)throw"unwind";},vg=!1,wg=null,Cg=0,ug=null,Dg=0,sg=0,tg=0,Hg=0,Eg=[],
Ig=[],Jg=[];function Lg(){wg=null;Cg++}var Mg=0;function zg(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Mg)Mg=b+1E3/60;else for(;b+2>=Mg;)Mg+=1E3/60;setTimeout(a,Math.max(Mg-b,0))}}var Gg={},yg,xg,Ag,Fg,yb=()=>{Lg();ug=null},zb=()=>{},Ab=()=>{Pe+=1;throw"unwind";};function Bb(){return r?H(6,1):"number"==typeof devicePixelRatio&&devicePixelRatio||1}function Ng(a){var b=P.Rc[a];b.target.removeEventListener(b.Pc,b.Ud,b.Vc);P.Rc.splice(a,1)}
function Og(){if(navigator.userActivation?navigator.userActivation.isActive:P.zd&&P.ne.vd){var a=P.ad;P.ad=[];for(var b of a)b.Fd(...b.Od)}}function Pg(a){if(!a.target)return-4;if(a.Wc)a.Ud=function(c){++P.zd;P.ne=a;Og();a.Xc(c);Og();--P.zd},a.target.addEventListener(a.Pc,a.Ud,a.Vc),P.Rc.push(a);else for(var b=0;b<P.Rc.length;++b)P.Rc[b].target==a.target&&P.Rc[b].Pc==a.Pc&&Ng(b--);return 0}function Qg(a){switch(a){case 1:return 0;case 2:return bf;default:return a}}
function Rg(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var P={Oe:0,df:0,Ad:0,sd:0,Jd:0,Hd:0,wd:0,Ye:0,mf:0,Xe:0,bf:0,Cd:0,wf:0,Gd:0,jf(a,b,c){w.set(w.subarray(b,b+c),a)},qf(){for(;P.Rc.length;)Ng(P.Rc.length-1);P.ad=[]},zd:0,ad:[],We(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of P.ad)if(e.Fd==a&&d(e.Od,c))return;P.ad.push({Fd:a,be:b,Od:c});P.ad.sort((f,g)=>f.be<g.be)},sf(a){P.ad=P.ad.filter(b=>b.Fd!=a)},Rc:[],rf:(a,b)=>{for(var c=0;c<P.Rc.length;++c)P.Rc[c].target!=a||b&&b!=P.Rc[c].Pc||
Ng(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Sg=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],Q=a=>{a=2<a?a?E(x,a):"":a;return Sg[a]||("undefined"!=typeof document?document.querySelector(a):null)},Tg=a=>0>Sg.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function Cb(a,b,c){if(r)return H(7,1,a,b,c);a=Q(a);if(!a)return-4;a=Tg(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0}
var Eb=()=>performance.now(),Fb=(a,b)=>{function c(d){I.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Gb=()=>{ab("OOM")},Ug=(a,b,c,d,e,f,g)=>{g=Qg(g);P.wd||(P.wd=R(256));a={target:Q(a),Pc:f,Wc:d,Xc:(l=event)=>{var m=Rg(l.target),n=l.target.id?l.target.id:"",q=g?R(256):P.wd;J(m,x,q+0,128);J(n,x,q+128,128);g?S(g,d,e,q,b):I.get(d)(e,q,b)&&l.preventDefault()},Vc:c};return Pg(a)};function Hb(a,b,c,d,e){return r?H(8,1,a,b,c,d,e):Ug(a,b,c,d,12,"blur",e)}
var Vg=(a,b,c)=>{a=Q(a);if(!a||a.Ue)return-4;var d=!1;a.ud?.ed&&(d=a.ud.ed.getParameter(2978),d=0===d[0]&&0===d[1]&&d[2]===a.width&&d[3]===a.height);a.width=b;a.height=c;d&&a.ud.ed.viewport(0,0,b,c);return 0};function Wg(a,b,c){return r?H(9,1,a,b,c):Vg(a,b,c)}var Ib=(a,b,c)=>Q(a)?Vg(a,b,c):Wg(a,b,c);function Jb(a,b,c,d,e){return r?H(10,1,a,b,c,d,e):Ug(a,b,c,d,13,"focus",e)}
var Xg=(a,b,c,d,e,f,g)=>{g=Qg(g);P.Ad||(P.Ad=R(160));a={target:Q(a),Pc:f,Wc:d,Xc:l=>{var m=g?R(160):P.Ad;A[m>>3]=l.timeStamp;var n=m>>2;y[n+2]=l.location;w[m+12]=l.ctrlKey;w[m+13]=l.shiftKey;w[m+14]=l.altKey;w[m+15]=l.metaKey;w[m+16]=l.repeat;y[n+5]=l.charCode;y[n+6]=l.keyCode;y[n+7]=l.which;J(l.key||"",x,m+32,32);J(l.code||"",x,m+64,32);J(l.char||"",x,m+96,32);J(l.locale||"",x,m+128,32);g?S(g,d,e,m,b):I.get(d)(e,m,b)&&l.preventDefault()},Vc:c};return Pg(a)};
function Kb(a,b,c,d,e){return r?H(11,1,a,b,c,d,e):Xg(a,b,c,d,2,"keydown",e)}function Lb(a,b,c,d,e){return r?H(12,1,a,b,c,d,e):Xg(a,b,c,d,1,"keypress",e)}function Mb(a,b,c,d,e){return r?H(13,1,a,b,c,d,e):Xg(a,b,c,d,3,"keyup",e)}
var Nb=(a,b,c)=>{a=I.get(a);Kg(a,b,c)},Yg=(a,b,c)=>{A[a>>3]=b.timeStamp;var d=a>>2;y[d+2]=b.screenX;y[d+3]=b.screenY;y[d+4]=b.clientX;y[d+5]=b.clientY;w[a+24]=b.ctrlKey;w[a+25]=b.shiftKey;w[a+26]=b.altKey;w[a+27]=b.metaKey;ua[2*d+14]=b.button;ua[2*d+15]=b.buttons;y[d+8]=b.movementX;y[d+9]=b.movementY;a=Tg(c);y[d+10]=b.clientX-(a.left|0);y[d+11]=b.clientY-(a.top|0)},Zg=(a,b,c,d,e,f,g)=>{g=Qg(g);P.sd||(P.sd=R(64));a=Q(a);return Pg({target:a,vd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Pc:f,Wc:d,
Xc:(l=event)=>{Yg(P.sd,l,a);if(g){var m=R(64);Yg(m,l,a);S(g,d,e,m,b)}else I.get(d)(e,P.sd,b)&&l.preventDefault()},Vc:c})};function Ob(a,b,c,d,e){return r?H(14,1,a,b,c,d,e):Zg(a,b,c,d,5,"mousedown",e)}function Pb(a,b,c,d,e){return r?H(15,1,a,b,c,d,e):Zg(a,b,c,d,33,"mouseenter",e)}function Qb(a,b,c,d,e){return r?H(16,1,a,b,c,d,e):Zg(a,b,c,d,34,"mouseleave",e)}function Rb(a,b,c,d,e){return r?H(17,1,a,b,c,d,e):Zg(a,b,c,d,8,"mousemove",e)}
function Sb(a,b,c,d,e){return r?H(18,1,a,b,c,d,e):Zg(a,b,c,d,6,"mouseup",e)}var $g=(a,b,c,d,e,f)=>{f=Qg(f);P.Cd||(P.Cd=R(257));return Pg({target:a,Pc:e,Wc:d,Xc:(g=event)=>{var l=f?R(257):P.Cd,m=document.pointerLockElement||document.Oc||document.hd||document.gd;w[l]=!!m;var n=m?.id||"";J(Rg(m),x,l+1,128);J(n,x,l+129,128);f?S(f,d,20,l,b):I.get(d)(20,l,b)&&g.preventDefault()},Vc:c})};
function Tb(a,b,c,d,e){if(r)return H(19,1,a,b,c,d,e);if(!document||!document.body||!(document.body.requestPointerLock||document.body.Oc||document.body.hd||document.body.gd))return-1;a=Q(a);if(!a)return-4;$g(a,b,c,d,"mozpointerlockchange",e);$g(a,b,c,d,"webkitpointerlockchange",e);$g(a,b,c,d,"mspointerlockchange",e);return $g(a,b,c,d,"pointerlockchange",e)}var ah=(a,b,c,d,e,f)=>{f=Qg(f);return Pg({target:a,Pc:e,Wc:d,Xc:(g=event)=>{f?S(f,d,38,0,b):I.get(d)(38,0,b)&&g.preventDefault()},Vc:c})};
function Ub(a,b,c,d,e){if(r)return H(20,1,a,b,c,d,e);if(!document||!(document.body.requestPointerLock||document.body.Oc||document.body.hd||document.body.gd))return-1;a=Q(a);if(!a)return-4;ah(a,b,c,d,"mozpointerlockerror",e);ah(a,b,c,d,"webkitpointerlockerror",e);ah(a,b,c,d,"mspointerlockerror",e);return ah(a,b,c,d,"pointerlockerror",e)}
var bh=(a,b,c,d,e)=>{e=Qg(e);P.Hd||(P.Hd=R(36));a=Q(a);return Pg({target:a,Pc:"resize",Wc:d,Xc:(f=event)=>{if(f.target==a){var g=document.body;if(g){var l=e?R(36):P.Hd;y[l>>2]=0;y[l+4>>2]=g.clientWidth;y[l+8>>2]=g.clientHeight;y[l+12>>2]=innerWidth;y[l+16>>2]=innerHeight;y[l+20>>2]=outerWidth;y[l+24>>2]=outerHeight;y[l+28>>2]=pageXOffset|0;y[l+32>>2]=pageYOffset|0;e?S(e,d,10,l,b):I.get(d)(10,l,b)&&f.preventDefault()}}},Vc:c})};function Vb(a,b,c,d,e){return r?H(21,1,a,b,c,d,e):bh(a,b,c,d,e)}
var ch=(a,b,c,d,e,f,g)=>{g=Qg(g);P.Gd||(P.Gd=R(1552));a=Q(a);return Pg({target:a,vd:"touchstart"==f||"touchend"==f,Pc:f,Wc:d,Xc:l=>{var m={},n=l.touches;for(var q of n)q.Xd=q.ae=0,m[q.identifier]=q;for(var v of l.changedTouches)v.Xd=1,m[v.identifier]=v;for(var D of l.targetTouches)m[D.identifier].ae=1;n=g?R(1552):P.Gd;A[n>>3]=l.timeStamp;w[n+12]=l.ctrlKey;w[n+13]=l.shiftKey;w[n+14]=l.altKey;w[n+15]=l.metaKey;q=n+16;v=Tg(a);D=0;for(let B of Object.values(m))if(m=q>>2,y[m]=B.identifier,y[m+1]=B.screenX,
y[m+2]=B.screenY,y[m+3]=B.clientX,y[m+4]=B.clientY,y[m+5]=B.pageX,y[m+6]=B.pageY,w[q+28]=B.Xd,w[q+29]=B.ae,y[m+8]=B.clientX-(v.left|0),y[m+9]=B.clientY-(v.top|0),q+=48,31<++D)break;y[n+8>>2]=D;g?S(g,d,e,n,b):I.get(d)(e,n,b)&&l.preventDefault()},Vc:c})};function Wb(a,b,c,d,e){return r?H(22,1,a,b,c,d,e):ch(a,b,c,d,25,"touchcancel",e)}function Xb(a,b,c,d,e){return r?H(23,1,a,b,c,d,e):ch(a,b,c,d,23,"touchend",e)}function Yb(a,b,c,d,e){return r?H(24,1,a,b,c,d,e):ch(a,b,c,d,24,"touchmove",e)}
function Zb(a,b,c,d,e){return r?H(25,1,a,b,c,d,e):ch(a,b,c,d,22,"touchstart",e)}
var T,dh=a=>{a.Ze=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},eh=a=>{a.hf=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},fh=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");return(a.getSupportedExtensions()||
[]).filter(c=>b.includes(c))},gh=1,hh=[],U=[],ih=[],jh=[],kh=[],W=[],lh=[],mh={},nh=[],oh={},ph=4,qh=0,rh=a=>{for(var b=gh++,c=a.length;c<b;c++)a[c]=null;return b},sh=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),g=f&&rh(d);f?(f.name=g,d[g]=f):X||=1282;y[b+4*e>>2]=g}},uh=(a,b)=>{a.Oc||(a.Oc=a.getContext,a.getContext=function(d,e){e=a.Oc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?th(c,b):0},th=(a,b)=>{var c=R(8);z[c+4>>2]=Ca();var d={handle:c,
attributes:b,version:b.Be,ed:a};a.canvas&&(a.canvas.ud=d);mh[c]=d;("undefined"==typeof b.Td||b.Td)&&vh(d);return c},vh=a=>{a||=wh;if(!a.ue){a.ue=!0;var b=a.ed;b.De=b.getExtension("WEBGL_multi_draw");b.re=b.getExtension("EXT_polygon_offset_clamp");b.qe=b.getExtension("EXT_clip_control");b.Me=b.getExtension("WEBGL_polygon_mode");dh(b);eh(b);2<=a.version&&(b.Rd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Rd)b.Rd=b.getExtension("EXT_disjoint_timer_query");fh(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},X,wh,xh=(a,b,c,d,e,f,g)=>{g=Qg(g);a={target:Q(a),Pc:f,Wc:d,Xc:(l=event)=>{g?S(g,d,e,0,b):I.get(d)(e,0,b)&&l.preventDefault()},Vc:c};Pg(a)};function $b(a,b,c,d,e){if(r)return H(26,1,a,b,c,d,e);xh(a,b,c,d,31,"webglcontextlost",e);return 0}function ac(a,b,c,d,e){if(r)return H(27,1,a,b,c,d,e);xh(a,b,c,d,32,"webglcontextrestored",e);return 0}
var yh=(a,b,c,d,e)=>{e=Qg(e);P.Jd||(P.Jd=R(96));return Pg({target:a,vd:!0,Pc:"wheel",Wc:d,Xc:(f=event)=>{var g=e?R(96):P.Jd;Yg(g,f,a);A[g+64>>3]=f.deltaX;A[g+72>>3]=f.deltaY;A[g+80>>3]=f.deltaZ;y[g+88>>2]=f.deltaMode;e?S(e,d,9,g,b):I.get(d)(9,g,b)&&f.preventDefault()},Vc:c})};function bc(a,b,c,d,e){return r?H(28,1,a,b,c,d,e):(a=Q(a))?"undefined"!=typeof a.onwheel?yh(a,b,c,d,e):-1:-4}
var zh=["default","low-power","high-performance"],cc=(a,b)=>{var c=b>>2;b={alpha:!!w[b+0],depth:!!w[b+1],stencil:!!w[b+2],antialias:!!w[b+3],premultipliedAlpha:!!w[b+4],preserveDrawingBuffer:!!w[b+5],powerPreference:zh[y[c+2]],failIfMajorPerformanceCaveat:!!w[b+12],Be:y[c+4],kf:y[c+5],Td:w[b+24],pe:w[b+25],nf:y[c+7],tf:w[b+32]};a=Q(a);return!a||b.pe?0:uh(a,b)},dc=(a,b)=>{a=mh[a];b=b?E(x,b):"";b.startsWith("GL_")&&(b=b.substr(3));"WEBGL_draw_instanced_base_vertex_base_instance"==b&&dh(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==
b&&eh(T);"WEBGL_multi_draw"==b&&(T.De=T.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(T.re=T.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(T.qe=T.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(T.Me=T.getExtension("WEBGL_polygon_mode"));return!!a.ed.getExtension(b)},ec=a=>{wh=mh[a];h.ctx=T=wh?.ed;return!a||T?0:-5},Ah={},Ch=()=>{if(!Bh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&
navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ah)void 0===Ah[b]?delete a[b]:a[b]=Ah[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Bh=c}return Bh},Bh;function fc(a,b){if(r)return H(29,1,a,b);var c=0;Ch().forEach((d,e)=>{var f=b+c;e=z[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++]=d.charCodeAt(f);w[e]=0;c+=d.length+1});return 0}
function gc(a,b){if(r)return H(30,1,a,b);var c=Ch();z[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);z[b>>2]=d;return 0}function ic(a){if(r)return H(31,1,a);try{var b=Yf(a);gg(b);return 0}catch(c){if("undefined"==typeof ng||"ErrnoError"!==c.name)throw c;return c.bd}}
function jc(a,b,c,d){if(r)return H(32,1,a,b,c,d);try{a:{var e=Yf(a);a=b;for(var f,g=b=0;g<c;g++){var l=z[a>>2],m=z[a+4>>2];a+=8;var n=e,q=f,v=w;if(0>m||0>q)throw new K(28);if(null===n.fd)throw new K(8);if(1===(n.flags&2097155))throw new K(8);if(M(n.node.mode))throw new K(31);if(!n.Mc.read)throw new K(28);var D="undefined"!=typeof q;if(!D)q=n.position;else if(!n.seekable)throw new K(70);var B=n.Mc.read(n,v,l,m,q);D||(n.position+=B);var F=B;if(0>F){var G=-1;break a}b+=F;if(F<m)break;"undefined"!=typeof f&&
(f+=F)}G=b}z[d>>2]=G;return 0}catch(V){if("undefined"==typeof ng||"ErrnoError"!==V.name)throw V;return V.bd}}
function kc(a,b,c,d,e){if(r)return H(33,1,a,b,c,d,e);b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Yf(a);hg(f,b,d);ve=[f.position>>>0,(ue=f.position,1<=+Math.abs(ue)?0<ue?+Math.floor(ue/4294967296)>>>0:~~+Math.ceil((ue-+(~~ue>>>0))/4294967296)>>>0:0)];y[e>>2]=ve[0];y[e+4>>2]=ve[1];f.yd&&0===b&&0===d&&(f.yd=null);return 0}catch(g){if("undefined"==typeof ng||"ErrnoError"!==g.name)throw g;return g.bd}}
function lc(a,b,c,d){if(r)return H(34,1,a,b,c,d);try{a:{var e=Yf(a);a=b;for(var f,g=b=0;g<c;g++){var l=z[a>>2],m=z[a+4>>2];a+=8;var n=ig(e,w,l,m,f);if(0>n){var q=-1;break a}b+=n;if(n<m)break;"undefined"!=typeof f&&(f+=n)}q=b}z[d>>2]=q;return 0}catch(v){if("undefined"==typeof ng||"ErrnoError"!==v.name)throw v;return v.bd}}
var mc=a=>T.activeTexture(a),nc=(a,b)=>{T.attachShader(U[a],W[b])},oc=(a,b)=>{35051==a?T.Qd=b:35052==a&&(T.$c=b);T.bindBuffer(a,hh[b])},pc=(a,b,c)=>{T.bindBufferBase(a,b,hh[c])},qc=(a,b)=>{T.bindFramebuffer(a,ih[b])},rc=(a,b)=>{T.bindRenderbuffer(a,jh[b])},sc=(a,b)=>{T.bindSampler(a,nh[b])},tc=(a,b)=>{T.bindTexture(a,kh[b])},uc=a=>{T.bindVertexArray(lh[a])},vc=(a,b,c,d)=>T.blendColor(a,b,c,d),wc=(a,b)=>T.blendEquationSeparate(a,b),xc=(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),yc=(a,b,c,d,e,f,g,l,m,n)=>
T.blitFramebuffer(a,b,c,d,e,f,g,l,m,n),zc=(a,b,c,d)=>{c&&b?T.bufferData(a,x,d,c,b):T.bufferData(a,b,d)},Ac=(a,b,c,d)=>{c&&T.bufferSubData(a,b,x,d,c)},Bc=a=>T.checkFramebufferStatus(a),Cc=(a,b,c,d)=>T.clearBufferfi(a,b,c,d),Dc=(a,b,c)=>{T.clearBufferfv(a,b,xa,c>>2)},Ec=(a,b,c)=>{T.clearBufferiv(a,b,y,c>>2)},Fc=(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},Gc=a=>{T.compileShader(W[a])},Hc=(a,b,c,d,e,f,g,l)=>{T.$c||!g?T.compressedTexImage2D(a,b,c,d,e,f,g,l):T.compressedTexImage2D(a,b,c,d,e,f,x,l,g)},Ic=
(a,b,c,d,e,f,g,l,m)=>{T.$c?T.compressedTexImage3D(a,b,c,d,e,f,g,l,m):T.compressedTexImage3D(a,b,c,d,e,f,g,x,m,l)},Jc=()=>{var a=rh(U),b=T.createProgram();b.name=a;b.qd=b.od=b.pd=0;b.Id=1;U[a]=b;return a},Kc=a=>{var b=rh(W);W[b]=T.createShader(a);return b},Lc=a=>T.cullFace(a),Mc=(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=hh[d];e&&(T.deleteBuffer(e),e.name=0,hh[d]=null,d==T.Qd&&(T.Qd=0),d==T.$c&&(T.$c=0))}},Nc=(a,b)=>{for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=ih[d];e&&(T.deleteFramebuffer(e),e.name=
0,ih[d]=null)}},Oc=a=>{if(a){var b=U[a];b?(T.deleteProgram(b),b.name=0,U[a]=null):X||=1281}},Pc=(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=jh[d];e&&(T.deleteRenderbuffer(e),e.name=0,jh[d]=null)}},Qc=(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=nh[d];e&&(T.deleteSampler(e),e.name=0,nh[d]=null)}},Rc=a=>{if(a){var b=W[a];b?(T.deleteShader(b),W[a]=null):X||=1281}},Sc=(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=kh[d];e&&(T.deleteTexture(e),e.name=0,kh[d]=null)}},Tc=(a,b)=>{for(var c=0;c<
a;c++){var d=y[b+4*c>>2];T.deleteVertexArray(lh[d]);lh[d]=null}},Uc=a=>T.depthFunc(a),Vc=a=>{T.depthMask(!!a)},Wc=a=>T.disable(a),Xc=a=>{T.disableVertexAttribArray(a)},Yc=(a,b,c)=>{T.drawArrays(a,b,c)},Zc=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Dh=[],$c=(a,b)=>{for(var c=Dh[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];T.drawBuffers(c)},ad=(a,b,c,d)=>{T.drawElements(a,b,c,d)},bd=(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},cd=a=>T.enable(a),dd=a=>{T.enableVertexAttribArray(a)},ed=(a,b,c,d)=>{T.framebufferRenderbuffer(a,
b,c,jh[d])},fd=(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,kh[d],e)},gd=(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,kh[c],d,e)},hd=a=>T.frontFace(a),jd=(a,b)=>{sh(a,b,"createBuffer",hh)},kd=(a,b)=>{sh(a,b,"createFramebuffer",ih)},ld=(a,b)=>{sh(a,b,"createRenderbuffer",jh)},md=(a,b)=>{sh(a,b,"createSampler",nh)},nd=(a,b)=>{sh(a,b,"createTexture",kh)},od=(a,b)=>{sh(a,b,"createVertexArray",lh)},pd=(a,b)=>T.getAttribLocation(U[a],b?E(x,b):""),Eh=()=>{var a=fh(T);return a=a.concat(a.map(b=>"GL_"+b))},Gh=
(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>wh.version){X||=1282;return}c=Eh().length;break;case 33307:case 33308:if(2>wh.version){X||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:X||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){X||=1280;u(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:X||=1280;u(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}y[b>>2]=c}else X||=1281},qd=
(a,b)=>Gh(a,b),rd=(a,b,c,d)=>{a=T.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?J(a,x,d,b):0;c&&(y[c>>2]=b)},sd=(a,b,c)=>{if(c)if(a>=gh)X||=1281;else if(a=U[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.qd){var d=T.getProgramParameter(a,35718);for(b=0;b<d;++b)a.qd=Math.max(a.qd,T.getActiveUniform(a,b).name.length+1)}y[c>>2]=a.qd}else if(35722==b){if(!a.od)for(d=T.getProgramParameter(a,35721),b=0;b<d;++b)a.od=Math.max(a.od,
T.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.od}else if(35381==b){if(!a.pd)for(d=T.getProgramParameter(a,35382),b=0;b<d;++b)a.pd=Math.max(a.pd,T.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.pd}else y[c>>2]=T.getProgramParameter(a,b);else X||=1281},td=(a,b,c,d)=>{a=T.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?J(a,x,d,b):0;c&&(y[c>>2]=b)},ud=(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(W[a]),
y[c>>2]=a?a.length+1:0):y[c>>2]=T.getShaderParameter(W[a],b):X||=1281},Hh=a=>{var b=rf(a)+1,c=R(b);c&&J(a,x,c,b);return c},vd=(a,b)=>{if(2>wh.version)return X||=1282,0;var c=oh[a];if(c)return 0>b||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=Eh().map(Hh),c=oh[a]=c,0>b||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},Ih=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),wd=(a,b)=>{b=b?E(x,b):"";if(a=U[a]){var c=a,d=c.md,e=c.ke,f;if(!d){c.md=d={};c.je={};var g=T.getProgramParameter(c,35718);
for(f=0;f<g;++f){var l=T.getActiveUniform(c,f);var m=l.name;l=l.size;var n=Ih(m);n=0<n?m.slice(0,n):m;var q=c.Id;c.Id+=l;e[n]=[l,q];for(m=0;m<l;++m)d[q]=m,c.je[q++]=n}}c=a.md;d=0;e=b;f=Ih(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.ke[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else X||=1281;return-1},xd=(a,b,c)=>{for(var d=Dh[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];T.invalidateFramebuffer(a,d)},yd=a=>{a=U[a];T.linkProgram(a);a.md=0;a.ke={}},zd=(a,b)=>{3317==a?ph=
b:3314==a&&(qh=b);T.pixelStorei(a,b)},Ad=(a,b)=>T.polygonOffset(a,b),Bd=a=>T.readBuffer(a),Cd=(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),Dd=(a,b,c)=>{T.samplerParameterf(nh[a],b,c)},Ed=(a,b,c)=>{T.samplerParameteri(nh[a],b,c)},Fd=(a,b,c,d)=>T.scissor(a,b,c,d),Gd=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=z[c+4*f>>2])?E(x,g,d?z[d+4*f>>2]:void 0):"";e+=g}T.shaderSource(W[a],e)},Hd=(a,b,c)=>T.stencilFunc(a,b,c),Id=(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),Jd=a=>T.stencilMask(a),Kd=
(a,b,c)=>T.stencilOp(a,b,c),Ld=(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),Jh=a=>{a-=5120;return 0==a?w:1==a?x:2==a?ua:4==a?y:6==a?xa:5==a||28922==a||28520==a||30779==a||30782==a?z:va},Kh=(a,b,c,d,e)=>{a=Jh(a);b=d*((qh||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ph-1&-ph);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Md=(a,b,c,d,e,f,g,l,m)=>{if(T.$c)T.texImage2D(a,b,c,d,e,f,g,l,m);else if(m){var n=
Jh(l);m>>>=31-Math.clz32(n.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,f,g,l,n,m)}else n=m?Kh(l,g,d,e,m):null,T.texImage2D(a,b,c,d,e,f,g,l,n)},Nd=(a,b,c,d,e,f,g,l,m,n)=>{if(T.$c)T.texImage3D(a,b,c,d,e,f,g,l,m,n);else if(n){var q=Jh(m);T.texImage3D(a,b,c,d,e,f,g,l,m,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,f,g,l,m,null)},Od=(a,b,c)=>T.texParameteri(a,b,c),Pd=(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),Qd=(a,b,c,d,e,f)=>T.texStorage3D(a,b,c,d,e,f),Rd=(a,b,c,d,e,f,g,l,m)=>{if(T.$c)T.texSubImage2D(a,
b,c,d,e,f,g,l,m);else if(m){var n=Jh(l);T.texSubImage2D(a,b,c,d,e,f,g,l,n,m>>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else m=m?Kh(l,g,e,f,m):null,T.texSubImage2D(a,b,c,d,e,f,g,l,m)},Sd=(a,b,c,d,e,f,g,l,m,n,q)=>{if(T.$c)T.texSubImage3D(a,b,c,d,e,f,g,l,m,n,q);else if(q){var v=Jh(n);T.texSubImage3D(a,b,c,d,e,f,g,l,m,n,v,q>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,b,c,d,e,f,g,l,m,n,null)},Y=a=>{var b=T.oe;if(b){var c=b.md[a];"number"==typeof c&&(b.md[a]=c=T.getUniformLocation(b,b.je[a]+
(0<c?`[${c}]`:"")));return c}X||=1282},Td=(a,b,c)=>{b&&T.uniform1fv(Y(a),xa,c>>2,b)},Ud=(a,b)=>{T.uniform1i(Y(a),b)},Vd=(a,b,c)=>{b&&T.uniform1iv(Y(a),y,c>>2,b)},Wd=(a,b,c)=>{b&&T.uniform2fv(Y(a),xa,c>>2,2*b)},Xd=(a,b,c)=>{b&&T.uniform2iv(Y(a),y,c>>2,2*b)},Yd=(a,b,c)=>{b&&T.uniform3fv(Y(a),xa,c>>2,3*b)},Zd=(a,b,c)=>{b&&T.uniform3iv(Y(a),y,c>>2,3*b)},$d=(a,b,c)=>{b&&T.uniform4fv(Y(a),xa,c>>2,4*b)},ae=(a,b,c)=>{b&&T.uniform4iv(Y(a),y,c>>2,4*b)},be=(a,b,c,d)=>{b&&T.uniformMatrix4fv(Y(a),!!c,xa,d>>2,
16*b)},ce=a=>{a=U[a];T.useProgram(a);T.oe=a},de=(a,b)=>{T.vertexAttribDivisor(a,b)},ee=(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,e,f)},fe=(a,b,c,d)=>T.viewport(a,b,c,d),ye=a=>{var b=rf(a)+1,c=Re(b);J(a,x,c,b);return c},xe=a=>{var b=Qe();a();Te(b)};r||Ye();Nf=Array(4096);ag(L,"/");O("/tmp");O("/home");O("/home/web_user");
(function(){O("/dev");vf(259,{read:()=>0,write:(d,e,f,g)=>g,dd:()=>0});dg("/dev/null",259);uf(1280,xf);uf(1536,yf);dg("/dev/tty",1280);dg("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=of(a).byteLength);return a[--b]};C("/dev","random",c);C("/dev","urandom",c);O("/dev/shm");O("/dev/shm/tmp")})();
(function(){O("/proc");var a=O("/proc/self");O("/proc/self/fd");ag({Yc(){var b=Bf(a,"fd",16895,73);b.Lc={lookup(c,d){var e=Yf(+d);c={parent:null,Yc:{Zd:"fake"},Lc:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=jg;h.FS_createDataFile=Gf;h.FS_createPreloadedFile=Hf;h.FS_unlink=eg;h.FS_createLazyFile=mg;h.FS_createDevice=C;L.Sd=new K(44);L.Sd.stack="<generic error, no stack>";h.requestAnimationFrame=zg;h.pauseMainLoop=Lg;
h.resumeMainLoop=function(){Cg++;var a=sg,b=tg,c=ug;ug=null;Kg(c,0,!1,Dg,!0);Bg(a,b);wg()};h.preMainLoop&&Ig.push(h.preMainLoop);h.postMainLoop&&Jg.push(h.postMainLoop);for(var Lh=0;32>Lh;++Lh)Dh.push(Array(Lh));
var rg=[ge,We,ff,mb,nb,ob,Bb,Cb,Hb,Wg,Jb,Kb,Lb,Mb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,fc,gc,ic,jc,kc,lc],ib,Z=function(){function a(c,d){Z=c.exports;Xe.push(Z.yc);I=Z.lc;Ma.unshift(Z.jc);ra=d;$a("wasm-instantiate");return Z}Za("wasm-instantiate");var b=hb();if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return u(`Module.instantiateWasm callback failed with error: ${c}`),!1}if(r)return new Promise(c=>{za=d=>{var e=new WebAssembly.Instance(d,hb());a(e,d);c()}});cb??=bb("db_skeleton.wasm")?
"db_skeleton.wasm":h.locateFile?h.locateFile("db_skeleton.wasm",t):t+"db_skeleton.wasm";gb(b,function(c){a(c.instance,c.module)});return{}}(),R=a=>(R=Z.mc)(a),ze=h.__sapp_emsc_onpaste=a=>(ze=h.__sapp_emsc_onpaste=Z.nc)(a),we=h.__sapp_html5_get_ask_leave_site=()=>(we=h.__sapp_html5_get_ask_leave_site=Z.oc)(),Ae=h.__sapp_emsc_begin_drop=a=>(Ae=h.__sapp_emsc_begin_drop=Z.pc)(a),Be=h.__sapp_emsc_drop=(a,b)=>(Be=h.__sapp_emsc_drop=Z.qc)(a,b),Ce=h.__sapp_emsc_end_drop=(a,b,c)=>(Ce=h.__sapp_emsc_end_drop=
Z.rc)(a,b,c);h.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,f,g,l)=>(h.__sapp_emsc_invoke_fetch_cb=Z.sc)(a,b,c,d,e,f,g,l);
var Mh=h._main=(a,b)=>(Mh=h._main=Z.tc)(a,b),De=h.__sfetch_emsc_head_response=(a,b)=>(De=h.__sfetch_emsc_head_response=Z.uc)(a,b),Fe=h.__sfetch_emsc_get_response=(a,b,c)=>(Fe=h.__sfetch_emsc_get_response=Z.vc)(a,b,c),Ee=h.__sfetch_emsc_failed_http_status=(a,b)=>(Ee=h.__sfetch_emsc_failed_http_status=Z.wc)(a,b),Ge=h.__sfetch_emsc_failed_buffer_too_small=a=>(Ge=h.__sfetch_emsc_failed_buffer_too_small=Z.xc)(a),Ca=()=>(Ca=Z.zc)(),S=(a,b,c,d,e)=>(S=Z.Ac)(a,b,c,d,e),Ea=(a,b,c,d,e,f)=>(Ea=Z.Bc)(a,b,c,d,
e,f),Ja=()=>(Ja=Z.Cc)(),Se=(a,b,c,d,e)=>(Se=Z.Dc)(a,b,c,d,e),$e=a=>($e=Z.Ec)(a),df=a=>(df=Z.Fc)(a),pg=()=>(pg=Z.Gc)(),cf=(a,b)=>(cf=Z.Hc)(a,b),Te=a=>(Te=Z.Ic)(a),Re=a=>(Re=Z.Jc)(a),Qe=()=>(Qe=Z.Kc)();h.___emscripten_embedded_file_data=241128;h.addRunDependency=Za;h.removeRunDependency=$a;h.FS_createPreloadedFile=Hf;h.FS_unlink=a=>eg(a);h.FS_createPath=jg;h.FS_createDevice=C;h.FS_createDataFile=(a,b,c,d,e,f)=>{Gf(a,b,c,d,e,f)};h.FS_createLazyFile=mg;var Nh;Ya=function Oh(){Nh||Ph();Nh||(Ya=Oh)};
function Qh(a=[]){var b=Mh;a.unshift(ea);var c=a.length,d=Re(4*(c+1)),e=d;a.forEach(g=>{z[e>>2]=ye(g);e+=4});z[e>>2]=0;try{var f=b(c,d);hc(f,!0)}catch(g){Ve(g)}}
function Ph(){var a=da;function b(){if(!Nh&&(Nh=!0,h.calledRun=!0,!sa&&(Qa(),r||Va(Oa),h.onRuntimeInitialized?.(),Rh&&Qh(a),!r))){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Pa.unshift(c)}Va(Pa)}}if(!(0<Wa))if(r)Qa(),startWorker(h);else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)La.unshift(h.preRun.shift());Va(La);0<Wa||(h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>
h.setStatus(""),1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Rh=!0;h.noInitialRun&&(Rh=!1);Ph();
