var g;g||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},g),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,r,t;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=w(a)?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};t=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};r=(a,b,c,d=!0)=>{a=w(a)?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof x||a.context instanceof x))throw a;});h=(a,b)=>{process.exitCode=a;throw b;}}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=q.startsWith("blob:")?"":q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1),fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
r=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=g.print||console.log.bind(console),y=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(h=g.quit);var z;g.wasmBinary&&(z=g.wasmBinary);"object"!=typeof WebAssembly&&ja("no native wasm support detected");
var A,ka=!1,la,B,C,ma,D,E,F,G;function na(){var a=A.buffer;g.HEAP8=la=new Int8Array(a);g.HEAP16=C=new Int16Array(a);g.HEAPU8=B=new Uint8Array(a);g.HEAPU16=ma=new Uint16Array(a);g.HEAP32=D=new Int32Array(a);g.HEAPU32=E=new Uint32Array(a);g.HEAPF32=F=new Float32Array(a);g.HEAPF64=G=new Float64Array(a)}var oa=[],pa=[],qa=[],ra=[];function sa(){var a=g.preRun.shift();oa.unshift(a)}var H=0,ta=null,I=null;
function ja(a){g.onAbort?.(a);a="Aborted("+a+")";y(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua=a=>a.startsWith("data:application/octet-stream;base64,"),w=a=>a.startsWith("file://"),J;J="sg_skeleton.wasm";if(!ua(J)){var va=J;J=g.locateFile?g.locateFile(va,q):q+va}function wa(a){if(a==J&&z)return new Uint8Array(z);if(t)return t(a);throw"both async and sync fetching of the wasm failed";}
function xa(a){if(!z&&(da||l)){if("function"==typeof fetch&&!w(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>wa(a));if(r)return new Promise((b,c)=>{r(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>wa(a))}function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{y(`failed to asynchronously prepare wasm: ${d}`);ja(d)})}
function za(a,b){var c=J;z||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||w(c)||ea||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){y(`wasm streaming compile failed: ${e}`);y("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}function x(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Aa=a=>{for(;0<a.length;)a.shift()(g)},Ba=g.noExitRuntime||!0,Ca="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,K=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Fa=a=>{var b=Da();a();Ea(b)},Ga=0,Ha=[];function Ia(){if(navigator.userActivation?navigator.userActivation.isActive:Ga&&Ja.rc)for(var a=0;a<Ha.length;++a){var b=Ha[a];Ha.splice(a,1);--a;b.Yc(...b.Qc)}}var L=[];function Ka(a){var b=L[a];b.target.removeEventListener(b.ec,b.xc,b.fc);L.splice(a,1)}
function M(a){if(!a.target)return-4;if(a.hc)a.xc=function(c){++Ga;Ja=a;Ia();a.ic(c);Ia();--Ga},a.target.addEventListener(a.ec,a.xc,a.fc),L.push(a);else for(var b=0;b<L.length;++b)L[b].target==a.target&&L[b].ec==a.ec&&Ka(b--);return 0}function La(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Ja,Ma,Na,Oa,Pa,Qa,Ra,Sa,Ta=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],N=a=>{a=2<a?a?K(B,a):"":a;return Ta[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ua=a=>0>Ta.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},O,P=(a,b,c)=>{var d=B;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.charCodeAt(k);if(55296<=f&&57343>=f){var m=a.charCodeAt(++k);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=
f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Va=(a,b,c,d,e,k)=>{Ma||=Q(256);a={target:N(a),ec:k,hc:d,ic:(f=event)=>{var m=f.target.id?f.target.id:"",n=Ma;P(La(f.target),n+0,128);P(m,n+128,128);O.get(d)(e,n,b)&&f.preventDefault()},fc:c};return M(a)},Wa=(a,b,c,d,e,k)=>{Na||=Q(176);a={target:N(a),ec:k,hc:d,ic:f=>{var m=Na;G[m>>3]=f.timeStamp;var n=
m>>2;D[n+2]=f.location;D[n+3]=f.ctrlKey;D[n+4]=f.shiftKey;D[n+5]=f.altKey;D[n+6]=f.metaKey;D[n+7]=f.repeat;D[n+8]=f.charCode;D[n+9]=f.keyCode;D[n+10]=f.which;P(f.key||"",m+44,32);P(f.code||"",m+76,32);P(f.char||"",m+108,32);P(f.locale||"",m+140,32);O.get(d)(e,m,b)&&f.preventDefault()},fc:c};return M(a)},Xa=(a,b,c)=>{G[a>>3]=b.timeStamp;a>>=2;D[a+2]=b.screenX;D[a+3]=b.screenY;D[a+4]=b.clientX;D[a+5]=b.clientY;D[a+6]=b.ctrlKey;D[a+7]=b.shiftKey;D[a+8]=b.altKey;D[a+9]=b.metaKey;C[2*a+20]=b.button;C[2*
a+21]=b.buttons;D[a+11]=b.movementX;D[a+12]=b.movementY;c=Ua(c);D[a+13]=b.clientX-(c.left|0);D[a+14]=b.clientY-(c.top|0)},R=(a,b,c,d,e,k)=>{Oa||=Q(72);a=N(a);return M({target:a,rc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,ec:k,hc:d,ic:(f=event)=>{Xa(Oa,f,a);O.get(d)(e,Oa,b)&&f.preventDefault()},fc:c})},Ya=(a,b,c,d,e)=>{Pa||=Q(260);return M({target:a,ec:e,hc:d,ic:(k=event)=>{var f=Pa,m=document.pointerLockElement||document.lc||document.zc||document.yc;D[f>>2]=!!m;var n=m?.id||"";P(La(m),f+4,
128);P(n,f+132,128);O.get(d)(20,f,b)&&k.preventDefault()},fc:c})},Za=(a,b,c,d,e)=>M({target:a,ec:e,hc:d,ic:(k=event)=>{O.get(d)(38,0,b)&&k.preventDefault()},fc:c}),$a=(a,b,c,d)=>{Qa||=Q(36);a=N(a);return M({target:a,ec:"resize",hc:d,ic:(e=event)=>{if(e.target==a){var k=document.body;if(k){var f=Qa;D[f>>2]=0;D[f+4>>2]=k.clientWidth;D[f+8>>2]=k.clientHeight;D[f+12>>2]=innerWidth;D[f+16>>2]=innerHeight;D[f+20>>2]=outerWidth;D[f+24>>2]=outerHeight;D[f+28>>2]=pageXOffset|0;D[f+32>>2]=pageYOffset|0;O.get(d)(10,
f,b)&&e.preventDefault()}}},fc:c})},ab=(a,b,c,d,e,k)=>{Ra||=Q(1696);a=N(a);return M({target:a,rc:"touchstart"==k||"touchend"==k,ec:k,hc:d,ic:f=>{for(var m,n={},p=f.touches,u=0;u<p.length;++u)m=p[u],m.Ac=m.Bc=0,n[m.identifier]=m;for(u=0;u<f.changedTouches.length;++u)m=f.changedTouches[u],m.Ac=1,n[m.identifier]=m;for(u=0;u<f.targetTouches.length;++u)n[f.targetTouches[u].identifier].Bc=1;p=Ra;G[p>>3]=f.timeStamp;var v=p>>2;D[v+3]=f.ctrlKey;D[v+4]=f.shiftKey;D[v+5]=f.altKey;D[v+6]=f.metaKey;v+=7;var kb=
Ua(a),lb=0;for(u in n)if(m=n[u],D[v]=m.identifier,D[v+1]=m.screenX,D[v+2]=m.screenY,D[v+3]=m.clientX,D[v+4]=m.clientY,D[v+5]=m.pageX,D[v+6]=m.pageY,D[v+7]=m.Ac,D[v+8]=m.Bc,D[v+9]=m.clientX-(kb.left|0),D[v+10]=m.clientY-(kb.top|0),v+=13,31<++lb)break;D[p+8>>2]=lb;O.get(d)(e,p,b)&&f.preventDefault()},fc:c})},bb=a=>{a.Sc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},cb=a=>{a.Tc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},db=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},eb=1,fb=[],S=[],gb=[],hb=[],ib=[],T=[],jb=[],mb=[],nb={},ob={},pb=a=>{for(var b=eb++,c=a.length;c<b;c++)a[c]=null;return b},qb=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=U[c](),f=k&&pb(d);k?(k.name=f,d[f]=k):V||=1282;D[b+4*e>>2]=f}},sb=(a,b)=>{a.lc||(a.lc=a.getContext,a.getContext=function(d,e){e=a.lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?rb(c,b):0},rb=(a,b)=>{var c=pb(mb),
d={handle:c,attributes:b,version:b.Nc,qc:a};a.canvas&&(a.canvas.Pc=d);mb[c]=d;("undefined"==typeof b.wc||b.wc)&&tb(d);return c},tb=a=>{a||=W;if(!a.Mc){a.Mc=!0;var b=a.qc;bb(b);cb(b);2<=a.version&&(b.vc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.vc)b.vc=b.getExtension("EXT_disjoint_timer_query");b.Oc=b.getExtension("WEBGL_multi_draw");db(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},V,W,ub=(a,b,c,d,e,k)=>{a={target:N(a),ec:k,hc:d,ic:(f=
event)=>{O.get(d)(e,0,b)&&f.preventDefault()},fc:c};M(a)},vb=(a,b,c,d)=>{Sa||=Q(104);return M({target:a,rc:!0,ec:"wheel",hc:d,ic:(e=event)=>{var k=Sa;Xa(k,e,a);G[k+72>>3]=e.deltaX;G[k+80>>3]=e.deltaY;G[k+88>>3]=e.deltaZ;D[k+96>>2]=e.deltaMode;O.get(d)(9,k,b)&&e.preventDefault()},fc:c})},wb=["default","low-power","high-performance"],xb=[null,[],[]];function yb(){var a=db(U);return a=a.concat(a.map(b=>"GL_"+b))}
var zb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){V||=1282;return}c=yb().length;break;case 33307:case 33308:if(2>W.version){V||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:V||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)D[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V||=1280;y(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:V||=1280;y(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}D[b>>2]=c}else V||=1281},Ab=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},X=a=>{var b=Ab(a)+1,c=Q(b);c&&P(a,c,b);return c},Bb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Cb=a=>{a-=5120;return 0==a?la:1==a?B:2==a?C:4==a?D:6==a?F:5==a||28922==a||28520==a||30779==a||30782==a?E:ma},Y=a=>{var b=U.Kc;if(b){var c=b.mc[a];"number"==typeof c&&(b.mc[a]=c=U.getUniformLocation(b,b.Ic[a]+(0<c?`[${c}]`:"")));return c}V||=1282},Db=a=>{Ba||(g.onExit?.(a),ka=!0);h(a,
new x(a))},Fb=a=>{var b=Ab(a)+1,c=Eb(b);P(a,c,b);return c},U,Rb={Sa:function(){var a=document.querySelector("input");a.onchange=b=>{var c=a.files;g.sc=c;Gb(c.length);for(let d=0;d<c.length;d++)Fa(()=>{const e=Fb(c[d].name);Hb(d,e)});Ib(b.clientX,b.clientY)}},Va:function(a){a=a?"60px":"0px";document.getElementById("canvas").style.top=a},oa:function(){return 0},ib:function(){return 0},jb:function(){},b:()=>{ja("")},ja:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ka:(a,b,c)=>{a=N(a);if(!a)return-4;
a=Ua(a);G[b>>3]=a.width;G[c>>3]=a.height;return 0},eb:(a,b,c)=>B.copyWithin(a,b,b+c),Wa:(a,b)=>{function c(d){O.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},db:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-A.buffer.byteLength+65535)/65536;try{A.grow(e);na();var k=1;break a}catch(f){}k=void 0}if(k)return!0}return!1},S:(a,
b,c,d)=>Va(a,b,c,d,12,"blur"),ia:(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>Va(a,b,c,d,13,"focus"),aa:(a,b,c,d)=>Wa(a,b,c,d,2,"keydown"),_:(a,b,c,d)=>Wa(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>Wa(a,b,c,d,3,"keyup"),ga:(a,b,c,d)=>R(a,b,c,d,5,"mousedown"),da:(a,b,c,d)=>R(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>R(a,b,c,d,34,"mouseleave"),ea:(a,b,c,d)=>R(a,b,c,d,8,"mousemove"),fa:(a,b,c,d)=>R(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||
document.body.lc||document.body.zc||document.body.yc))return-1;a=N(a);if(!a)return-4;Ya(a,b,c,d,"mozpointerlockchange");Ya(a,b,c,d,"webkitpointerlockchange");Ya(a,b,c,d,"mspointerlockchange");return Ya(a,b,c,d,"pointerlockchange")},U:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.lc||document.body.zc||document.body.yc))return-1;a=N(a);if(!a)return-4;Za(a,b,c,d,"mozpointerlockerror");Za(a,b,c,d,"webkitpointerlockerror");Za(a,b,c,d,"mspointerlockerror");return Za(a,b,c,
d,"pointerlockerror")},Xa:(a,b,c,d)=>$a(a,b,c,d),W:(a,b,c,d)=>ab(a,b,c,d,25,"touchcancel"),X:(a,b,c,d)=>ab(a,b,c,d,23,"touchend"),Y:(a,b,c,d)=>ab(a,b,c,d,24,"touchmove"),Z:(a,b,c,d)=>ab(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{ub(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{ub(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?vb(a,b,c,d):-1:-4,ha:(a,b)=>{b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+
4],preserveDrawingBuffer:!!D[b+5],powerPreference:wb[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],Nc:D[b+8],Uc:D[b+9],wc:D[b+10],Lc:D[b+11],Vc:D[b+12],Wc:D[b+13]};a=N(a);return!a||b.Lc?0:sb(a,b)},Ta:(a,b)=>{a=mb[a];b=b?K(B,b):"";b.startsWith("GL_")&&(b=b.substr(3));"WEBGL_draw_instanced_base_vertex_base_instance"==b&&bb(U);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&cb(U);"WEBGL_multi_draw"==b&&(U.Oc=U.getExtension("WEBGL_multi_draw"));return!!a.qc.getExtension(b)},Ua:a=>{W=mb[a];
g.Rc=U=W?.qc;return!a||U?0:-5},na:()=>52,gb:()=>52,cb:function(){return 70},fb:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var f=E[b>>2],m=E[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=B[f+n],u=xb[a];0===p||10===p?((1===a?ia:y)(K(u,0)),u.length=0):u.push(p)}e+=m}E[d>>2]=e;return 0},h:a=>U.activeTexture(a),C:(a,b)=>{U.attachShader(S[a],T[b])},c:(a,b)=>{35051==a?U.uc=b:35052==a&&(U.kc=b);U.bindBuffer(a,fb[b])},i:(a,b)=>{U.bindFramebuffer(a,gb[b])},F:(a,b)=>{U.bindRenderbuffer(a,hb[b])},a:(a,b)=>{U.bindTexture(a,
ib[b])},O:a=>{U.bindVertexArray(jb[a])},K:(a,b,c,d)=>U.blendColor(a,b,c,d),L:(a,b)=>U.blendEquationSeparate(a,b),M:(a,b,c,d)=>U.blendFuncSeparate(a,b,c,d),q:(a,b,c,d,e,k,f,m,n,p)=>U.blitFramebuffer(a,b,c,d,e,k,f,m,n,p),Ga:(a,b,c,d)=>{c&&b?U.bufferData(a,B,d,c,b):U.bufferData(a,b,d)},m:(a,b,c,d)=>{c&&U.bufferSubData(a,b,B,d,c)},Cb:a=>U.clear(a),sa:(a,b,c,d)=>U.clearColor(a,b,c,d),ra:a=>U.clearDepth(a),Db:a=>U.clearStencil(a),k:(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,!!d)},Hb:a=>{U.compileShader(T[a])},
Ca:(a,b,c,d,e,k,f,m)=>{U.kc||!f?U.compressedTexImage2D(a,b,c,d,e,k,f,m):U.compressedTexImage2D(a,b,c,d,e,k,B,m,f)},Aa:(a,b,c,d,e,k,f,m,n)=>{U.kc?U.compressedTexImage3D(a,b,c,d,e,k,f,m,n):U.compressedTexImage3D(a,b,c,d,e,k,f,B,n,m)},ya:()=>{var a=pb(S),b=U.createProgram();b.name=a;b.pc=b.nc=b.oc=0;b.tc=1;S[a]=b;return a},Jb:a=>{var b=pb(T);T[b]=U.createShader(a);return b},H:a=>U.cullFace(a),Pa:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=fb[d];e&&(U.deleteBuffer(e),e.name=0,fb[d]=null,d==U.uc&&
(U.uc=0),d==U.kc&&(U.kc=0))}},j:(a,b)=>{for(var c=0;c<a;++c){var d=D[b+4*c>>2],e=gb[d];e&&(U.deleteFramebuffer(e),e.name=0,gb[d]=null)}},z:a=>{if(a){var b=S[a];b?(U.deleteProgram(b),b.name=0,S[a]=null):V||=1281}},P:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=hb[d];e&&(U.deleteRenderbuffer(e),e.name=0,hb[d]=null)}},v:a=>{if(a){var b=T[a];b?(U.deleteShader(b),T[a]=null):V||=1281}},Oa:(a,b)=>{for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=ib[d];e&&(U.deleteTexture(e),e.name=0,ib[d]=null)}},Na:(a,b)=>
{for(var c=0;c<a;c++){var d=D[b+4*c>>2];U.deleteVertexArray(jb[d]);jb[d]=null}},y:a=>U.depthFunc(a),x:a=>{U.depthMask(!!a)},e:a=>U.disable(a),N:a=>{U.disableVertexAttribArray(a)},kb:(a,b,c)=>{U.drawArrays(a,b,c)},lb:(a,b,c,d)=>{U.drawArraysInstanced(a,b,c,d)},mb:(a,b,c,d)=>{U.drawElements(a,b,c,d)},nb:(a,b,c,d,e)=>{U.drawElementsInstanced(a,b,c,d,e)},g:a=>U.enable(a),yb:a=>{U.enableVertexAttribArray(a)},I:a=>U.frontFace(a),Ha:(a,b)=>{qb(a,b,"createBuffer",fb)},G:(a,b)=>{qb(a,b,"createRenderbuffer",
hb)},Ea:(a,b)=>{qb(a,b,"createTexture",ib)},Ma:(a,b)=>{qb(a,b,"createVertexArray",jb)},Fb:(a,b)=>U.getAttribLocation(S[a],b?K(B,b):""),d:(a,b)=>zb(a,b),Kb:(a,b,c,d)=>{a=U.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?P(a,d,b):0;c&&(D[c>>2]=b)},va:(a,b,c)=>{if(c)if(a>=eb)V||=1281;else if(a=S[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.pc)for(b=0;b<U.getProgramParameter(a,35718);++b)a.pc=Math.max(a.pc,U.getActiveUniform(a,
b).name.length+1);D[c>>2]=a.pc}else if(35722==b){if(!a.nc)for(b=0;b<U.getProgramParameter(a,35721);++b)a.nc=Math.max(a.nc,U.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.nc}else if(35381==b){if(!a.oc)for(b=0;b<U.getProgramParameter(a,35382);++b)a.oc=Math.max(a.oc,U.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.oc}else D[c>>2]=U.getProgramParameter(a,b);else V||=1281},Gb:(a,b,c,d)=>{a=U.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?P(a,d,b):0;c&&(D[c>>2]=b)},ta:(a,b,c)=>{c?35716==
b?(a=U.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),D[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(T[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=U.getShaderParameter(T[a],b):V||=1281},Ra:a=>{var b=nb[a];if(!b){switch(a){case 7939:b=X(yb().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||(V||=1280);b=b?X(b):0;break;case 7938:b=X(`OpenGL ES 3.0 (${U.getParameter(7938)})`);break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=X(b);break;default:V||=1280}nb[a]=b}return b},Qa:(a,b)=>{if(2>W.version)return V||=1282,0;var c=ob[a];if(c)return 0>b||b>=c.length?(V||=1281,0):c[b];switch(a){case 7939:return c=yb().map(X),c=ob[a]=c,0>b||b>=c.length?(V||=1281,0):c[b];default:return V||=1280,0}},u:(a,b)=>{b=b?K(B,b):"";if(a=S[a]){var c=a,d=c.mc,e=c.Jc,k;if(!d)for(c.mc=d={},c.Ic={},k=0;k<U.getProgramParameter(c,35718);++k){var f=U.getActiveUniform(c,k);
var m=f.name;f=f.size;var n=Bb(m);n=0<n?m.slice(0,n):m;var p=c.tc;c.tc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Ic[p++]=n}c=a.mc;d=0;e=b;k=Bb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Jc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else V||=1281;return-1},xa:a=>{a=S[a];U.linkProgram(a);a.mc=0;a.Jc={}},La:(a,b)=>{U.pixelStorei(a,b)},J:(a,b)=>U.polygonOffset(a,b),r:a=>U.readBuffer(a),Fa:(a,b,c,d)=>U.renderbufferStorage(a,b,c,d),E:(a,b,c,d,e)=>U.renderbufferStorageMultisample(a,
b,c,d,e),s:(a,b,c,d)=>U.scissor(a,b,c,d),Ib:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var f=(f=E[c+4*k>>2])?K(B,f,d?E[d+4*k>>2]:void 0):"";e+=f}U.shaderSource(T[a],e)},Ka:(a,b,c)=>U.stencilFunc(a,b,c),qa:(a,b,c,d)=>U.stencilFuncSeparate(a,b,c,d),w:a=>U.stencilMask(a),Ja:(a,b,c)=>U.stencilOp(a,b,c),pa:(a,b,c,d)=>U.stencilOpSeparate(a,b,c,d),Ba:(a,b,c,d,e,k,f,m,n)=>{if(U.kc)U.texImage2D(a,b,c,d,e,k,f,m,n);else if(n){var p=Cb(m);U.texImage2D(a,b,c,d,e,k,f,m,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else U.texImage2D(a,
b,c,d,e,k,f,m,null)},za:(a,b,c,d,e,k,f,m,n,p)=>{if(U.kc)U.texImage3D(a,b,c,d,e,k,f,m,n,p);else if(p){var u=Cb(n);U.texImage3D(a,b,c,d,e,k,f,m,n,u,p>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else U.texImage3D(a,b,c,d,e,k,f,m,n,null)},D:(a,b,c)=>U.texParameterf(a,b,c),f:(a,b,c)=>U.texParameteri(a,b,c),xb:(a,b,c)=>{b&&U.uniform1fv(Y(a),F,c>>2,b)},ua:(a,b)=>{U.uniform1i(Y(a),b)},tb:(a,b,c)=>{b&&U.uniform1iv(Y(a),D,c>>2,b)},wb:(a,b,c)=>{b&&U.uniform2fv(Y(a),F,c>>2,2*b)},sb:(a,b,c)=>{b&&U.uniform2iv(Y(a),D,
c>>2,2*b)},vb:(a,b,c)=>{b&&U.uniform3fv(Y(a),F,c>>2,3*b)},rb:(a,b,c)=>{b&&U.uniform3iv(Y(a),D,c>>2,3*b)},ub:(a,b,c)=>{b&&U.uniform4fv(Y(a),F,c>>2,4*b)},qb:(a,b,c)=>{b&&U.uniform4iv(Y(a),D,c>>2,4*b)},ob:(a,b,c,d)=>{b&&U.uniformMatrix4fv(Y(a),!!c,F,d>>2,16*b)},l:a=>{a=S[a];U.useProgram(a);U.Kc=a},zb:(a,b)=>{U.vertexAttribDivisor(a,b)},Bb:(a,b,c,d,e,k)=>{U.vertexAttribPointer(a,b,c,!!d,e,k)},t:(a,b,c,d)=>U.viewport(a,b,c,d),Ia:function(){g.Cc=a=>{0!=Jb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
g.Cc)},Lb:function(){g.Hc=a=>{const b=a.clipboardData.getData("text");Fa(()=>{const c=Fb(b);Kb(c)})};window.addEventListener("paste",g.Hc)},pb:function(a){g.Xc=[];a=a?K(B,a):"";a=document.getElementById(a);g.Dc=b=>{b.stopPropagation();b.preventDefault()};g.Ec=b=>{b.stopPropagation();b.preventDefault()};g.Fc=b=>{b.stopPropagation();b.preventDefault()};g.Gc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.sc=c;Gb(c.length);for(let d=0;d<c.length;d++)Fa(()=>{const e=Fb(c[d].name);
Hb(d,e)});Ib(b.clientX,b.clientY)};a.addEventListener("dragenter",g.Dc,!1);a.addEventListener("dragleave",g.Ec,!1);a.addEventListener("dragover",g.Fc,!1);a.addEventListener("drop",g.Gc,!1)},Za:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},p:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Lb()});document.body.append(a)},hb:function(a){const b=
g.sc;return 0>a||a>=b.length?0:b[a].size},bb:function(a,b,c,d,e){const k=new FileReader;k.onload=f=>{f=f.target.result;f.byteLength>d?Mb(a,0,1,b,0,c,d,e):(B.set(new Uint8Array(f),c),Mb(a,1,0,b,f.byteLength,c,d,e))};k.onerror=()=>{Mb(a,0,2,b,0,c,d,e)};k.readAsArrayBuffer(g.sc[a])},o:function(){document.getElementById("_sokol_app_input_element").focus()},$a:function(a){a=a?K(B,a):"";g.jc=document.getElementById(a);g.jc||console.log("sokol_app.h: invalid target:"+a);g.jc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},Da:function(){window.removeEventListener("beforeunload",g.Cc)},Eb:function(){window.removeEventListener("paste",g.Hc)},ab:function(a){a=a?K(B,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",g.Dc);a.removeEventListener("dragleave",g.Ec);a.removeEventListener("dragover",g.Fc);a.removeEventListener("drop",g.Gc)},B:function(){g.jc&&g.jc.requestPointerLock&&g.jc.requestPointerLock()},_a:function(a,b){if(g.jc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";
break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.jc.style.cursor=a}},Ya:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(B.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},n:function(){document.getElementById("_sokol_app_input_element").blur()},Ab:function(a){a=a?K(B,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);
b.select();document.execCommand("copy");document.body.removeChild(b)},A:function(a,b,c,d,e,k){b=b?K(B,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),p=n.length;p<=k?(B.set(n,e),Nb(a,d,p)):Ob(a)}else Pb(a,f.status)};f.send()},la:function(a,b){b=b?K(B,b):"";const c=
new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Qb(a,d)}else Pb(a,c.status)};c.send()},ma:function(){return navigator.userAgent.includes("Macintosh")?1:0},wa:function(a,b){b=b?K(B,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;A=Z.Mb;na();O=Z.ac;pa.unshift(Z.Nb);
H--;g.monitorRunDependencies?.(H);0==H&&(null!==ta&&(clearInterval(ta),ta=null),I&&(c=I,I=null,c()));return Z}var b={a:Rb};H++;g.monitorRunDependencies?.(H);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return y(`Module.instantiateWasm callback failed with error: ${c}`),!1}za(b,function(c){a(c.instance)});return{}}(),Q=a=>(Q=Z.Ob)(a),Lb=g.__sapp_emsc_notify_keyboard_hidden=()=>(Lb=g.__sapp_emsc_notify_keyboard_hidden=Z.Pb)(),Kb=g.__sapp_emsc_onpaste=a=>(Kb=g.__sapp_emsc_onpaste=
Z.Qb)(a),Jb=g.__sapp_html5_get_ask_leave_site=()=>(Jb=g.__sapp_html5_get_ask_leave_site=Z.Rb)(),Gb=g.__sapp_emsc_begin_drop=a=>(Gb=g.__sapp_emsc_begin_drop=Z.Sb)(a),Hb=g.__sapp_emsc_drop=(a,b)=>(Hb=g.__sapp_emsc_drop=Z.Tb)(a,b),Ib=g.__sapp_emsc_end_drop=(a,b)=>(Ib=g.__sapp_emsc_end_drop=Z.Ub)(a,b),Mb=g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,f,m)=>(Mb=g.__sapp_emsc_invoke_fetch_cb=Z.Vb)(a,b,c,d,e,k,f,m),Sb=g._main=(a,b)=>(Sb=g._main=Z.Wb)(a,b);g.__saudio_emsc_pull=a=>(g.__saudio_emsc_pull=Z.Xb)(a);
var Qb=g.__sfetch_emsc_head_response=(a,b)=>(Qb=g.__sfetch_emsc_head_response=Z.Yb)(a,b),Nb=g.__sfetch_emsc_get_response=(a,b,c)=>(Nb=g.__sfetch_emsc_get_response=Z.Zb)(a,b,c),Pb=g.__sfetch_emsc_failed_http_status=(a,b)=>(Pb=g.__sfetch_emsc_failed_http_status=Z._b)(a,b),Ob=g.__sfetch_emsc_failed_buffer_too_small=a=>(Ob=g.__sfetch_emsc_failed_buffer_too_small=Z.$b)(a),Da=()=>(Da=Z.bc)(),Ea=a=>(Ea=Z.cc)(a),Eb=a=>(Eb=Z.dc)(a);g.___start_em_js=40260;g.___stop_em_js=50364;var Tb;
I=function Ub(){Tb||Vb();Tb||(I=Ub)};function Wb(a=[]){var b=Sb;a.unshift(ca);var c=a.length,d=Eb(4*(c+1)),e=d;a.forEach(f=>{E[e>>2]=Fb(f);e+=4});E[e>>2]=0;try{var k=b(c,d);Db(k)}catch(f){f instanceof x||"unwind"==f||h(1,f)}}
function Vb(){var a=ba;function b(){if(!Tb&&(Tb=!0,g.calledRun=!0,!ka)){Aa(pa);Aa(qa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();Xb&&Wb(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ra.unshift(c)}Aa(ra)}}if(!(0<H)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)sa();Aa(oa);0<H||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Xb=!0;g.noInitialRun&&(Xb=!1);Vb();
