var f;f||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,h="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");m=h?ka.dirname(m)+"/":__dirname+"/";ha=(a,b)=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c,d=!0)=>{a=la(a)?new URL(a):ka.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,k)=>{e?c(e):b(d?k.buffer:k)})};!f.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;});da=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||h)h?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),m=m.startsWith("blob:")?"":m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1),ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},h&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=f.print||console.log.bind(console),r=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);f.quit&&(da=f.quit);var u;f.wasmBinary&&(u=f.wasmBinary);"object"!=typeof WebAssembly&&oa("no native wasm support detected");
var pa,v=!1,w,qa,x,ra,sa,y,z,A,B,ta=[],ua=[],va=[],wa=[];function xa(){var a=f.preRun.shift();ta.unshift(a)}var C=0,ya=null,D=null;function oa(a){f.onAbort?.(a);a="Aborted("+a+")";r(a);v=!0;w=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var za=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),E;E="sg_skeleton2.wasm";if(!za(E)){var Aa=E;E=f.locateFile?f.locateFile(Aa,m):m+Aa}
function Ba(a){if(a==E&&u)return new Uint8Array(u);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Ca(a){if(!u&&(ea||h)){if("function"==typeof fetch&&!la(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Ba(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ba(a))}
function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{r(`failed to asynchronously prepare wasm: ${d}`);oa(d)})}function Ea(a,b){var c=E;u||"function"!=typeof WebAssembly.instantiateStreaming||za(c)||la(c)||fa||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r(`wasm streaming compile failed: ${e}`);r("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}
function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Fa=a=>{for(;0<a.length;)a.shift()(f)},Ga=f.noExitRuntime||!0,Pa=(a,b)=>{Ha=a;Ia=b;if(F)if(Ja||=!0,0==a)G=function(){var d=Math.max(0,Ka+b-La())|0;setTimeout(Ma,d)};else if(1==a)G=function(){Na(Ma)};else if(2==a){if("undefined"==typeof Oa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oa=function(d){c.push(d);h?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),
postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Oa=setImmediate;G=function(){Oa(Ma)}}},La;La=()=>performance.now();
var Xa=(a,b,c,d,e)=>{F=a;Qa=d;var k=H;Ja=!1;Ma=function(){if(!v)if(0<Ra.length){var g=Ra.shift();g.Uc(g.Pc);if(Sa){var l=Sa,n=0==l%1?l-1:Math.floor(l);Sa=g.Rc?n:(8*l+(n+.5))/9}f.setStatus&&(g=f.statusMessage||"Please wait...",l=Sa,n=Ta.Tc,l?l<n?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(g):f.setStatus(""));k<H||setTimeout(Ma,0)}else if(!(k<H))if(Ua=Ua+1|0,1==Ha&&1<Ia&&0!=Ua%Ia)G();else{0==Ha&&(Ka=La());if(!(v||f.preMainLoop&&!1===f.preMainLoop())){if(!v)try{if(a(),!Ga)try{w=
g=w,Va(g)}catch(p){Wa(p)}}catch(p){Wa(p)}f.postMainLoop?.()}k<H||("object"==typeof SDL&&SDL.audio?.Yc?.(),G())}};e||(b&&0<b?Pa(0,1E3/b):Pa(1,1),G());if(c)throw"unwind";},Wa=a=>{a instanceof ma||"unwind"==a||da(1,a)},Va=a=>{w=a;Ga||(f.onExit?.(a),v=!0);da(a,new ma(a))},Ya=a=>{w=a;Va(a)},Ja=!1,G=null,H=0,F=null,Qa=0,Ha=0,Ia=0,Ua=0,Ra=[];function Za(){G=null;H++}var Ta={},Ka,Ma,Sa,$a=!1,ab=!1,bb=[];
function cb(){function a(){ab=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!db){db=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!ab&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}var eb=!1,fb=void 0,I=void 0;
function gb(){if(!$a)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var hb=0;function Na(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===hb)hb=b+1E3/60;else for(;b+2>=hb;)hb+=1E3/60;setTimeout(a,Math.max(hb-b,0))}}var ib=[];function jb(){var a=f.canvas;ib.forEach(b=>b(a.width,a.height))}
function kb(a,b,c){b&&c?(a.Nc=b,a.Kc=c):(b=a.Nc,c=a.Kc);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var k=Math.min(screen.width/d,screen.height/e);d=Math.round(d*k);e=Math.round(e*
k)}I?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Oa,db,nb=a=>{var b=lb();a();mb(b)},ob=0,pb=[];
function qb(){if(navigator.userActivation?navigator.userActivation.isActive:ob&&rb.oc)for(var a=0;a<pb.length;++a){var b=pb[a];pb.splice(a,1);--a;b.bd(...b.Qc)}}var J=[];function sb(a){var b=J[a];b.target.removeEventListener(b.bc,b.wc,b.cc);J.splice(a,1)}function K(a){if(!a.target)return-4;if(a.dc)a.wc=function(c){++ob;rb=a;qb();a.ec(c);qb();--ob},a.target.addEventListener(a.bc,a.wc,a.cc),J.push(a);else for(var b=0;b<J.length;++b)J[b].target==a.target&&J[b].bc==a.bc&&sb(b--);return 0}
function tb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var rb,ub,vb,wb,xb,yb,zb,Ab,Bb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Bb)return Bb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|g:(e&7)<<18|k<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?L(x,a):"":a;return Cb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Db=a=>0>Cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},N,O=(a,b,c)=>{var d=x;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var l=a.charCodeAt(++k);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;
d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Eb=(a,b,c,d,e,k)=>{ub||=P(256);a={target:M(a),bc:k,dc:d,ec:(g=event)=>{var l=g.target.id?g.target.id:"",n=ub;O(tb(g.target),n+0,128);O(l,n+128,128);N.get(d)(e,n,b)&&g.preventDefault()},cc:c};return K(a)},Fb=(a,b,c,d,e,k)=>{vb||=P(176);a={target:M(a),bc:k,dc:d,ec:g=>{var l=vb;B[l>>3]=g.timeStamp;var n=l>>2;y[n+2]=g.location;
y[n+3]=g.ctrlKey;y[n+4]=g.shiftKey;y[n+5]=g.altKey;y[n+6]=g.metaKey;y[n+7]=g.repeat;y[n+8]=g.charCode;y[n+9]=g.keyCode;y[n+10]=g.which;O(g.key||"",l+44,32);O(g.code||"",l+76,32);O(g.char||"",l+108,32);O(g.locale||"",l+140,32);N.get(d)(e,l,b)&&g.preventDefault()},cc:c};return K(a)},Gb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;y[a+6]=b.ctrlKey;y[a+7]=b.shiftKey;y[a+8]=b.altKey;y[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;y[a+
11]=b.movementX;y[a+12]=b.movementY;c=Db(c);y[a+13]=b.clientX-(c.left|0);y[a+14]=b.clientY-(c.top|0)},Hb=(a,b,c,d,e,k)=>{wb||=P(72);a=M(a);return K({target:a,oc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,bc:k,dc:d,ec:(g=event)=>{Gb(wb,g,a);N.get(d)(e,wb,b)&&g.preventDefault()},cc:c})},Ib=(a,b,c,d,e)=>{xb||=P(260);return K({target:a,bc:e,dc:d,ec:(k=event)=>{var g=xb,l=document.pointerLockElement||document.hc||document.tc||document.rc;y[g>>2]=!!l;var n=l?.id||"";O(tb(l),g+4,128);O(n,g+132,128);
N.get(d)(20,g,b)&&k.preventDefault()},cc:c})},Jb=(a,b,c,d,e)=>K({target:a,bc:e,dc:d,ec:(k=event)=>{N.get(d)(38,0,b)&&k.preventDefault()},cc:c}),Kb=(a,b,c,d)=>{yb||=P(36);a=M(a);return K({target:a,bc:"resize",dc:d,ec:(e=event)=>{if(e.target==a){var k=document.body;if(k){var g=yb;y[g>>2]=0;y[g+4>>2]=k.clientWidth;y[g+8>>2]=k.clientHeight;y[g+12>>2]=innerWidth;y[g+16>>2]=innerHeight;y[g+20>>2]=outerWidth;y[g+24>>2]=outerHeight;y[g+28>>2]=pageXOffset|0;y[g+32>>2]=pageYOffset|0;N.get(d)(10,g,b)&&e.preventDefault()}}},
cc:c})},Lb=(a,b,c,d,e,k)=>{zb||=P(1696);a=M(a);return K({target:a,oc:"touchstart"==k||"touchend"==k,bc:k,dc:d,ec:g=>{for(var l,n={},p=g.touches,q=0;q<p.length;++q)l=p[q],l.xc=l.zc=0,n[l.identifier]=l;for(q=0;q<g.changedTouches.length;++q)l=g.changedTouches[q],l.xc=1,n[l.identifier]=l;for(q=0;q<g.targetTouches.length;++q)n[g.targetTouches[q].identifier].zc=1;p=zb;B[p>>3]=g.timeStamp;var t=p>>2;y[t+3]=g.ctrlKey;y[t+4]=g.shiftKey;y[t+5]=g.altKey;y[t+6]=g.metaKey;t+=7;var Mb=Db(a),Nb=0;for(q in n)if(l=
n[q],y[t]=l.identifier,y[t+1]=l.screenX,y[t+2]=l.screenY,y[t+3]=l.clientX,y[t+4]=l.clientY,y[t+5]=l.pageX,y[t+6]=l.pageY,y[t+7]=l.xc,y[t+8]=l.zc,y[t+9]=l.clientX-(Mb.left|0),y[t+10]=l.clientY-(Mb.top|0),t+=13,31<++Nb)break;y[p+8>>2]=Nb;N.get(d)(e,p,b)&&g.preventDefault()},cc:c})},Ob=a=>{a.Sc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Pb=a=>{a.Vc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Qb=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Rb=1,Sb=[],Q=[],Tb=[],Ub=[],R=[],S=[],Vb=[],Wb=[],T=[],Xb={},Yb=4,Zb=a=>{for(var b=Rb++,c=a.length;c<b;c++)a[c]=null;return b},W=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=U[c](),g=k&&Zb(d);k?(k.name=g,d[g]=k):V||=1282;y[b+4*e>>2]=g}},ac=(a,b)=>{a.hc||(a.hc=a.getContext,a.getContext=function(d,e){e=a.hc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?$b(c,b):0},$b=(a,b)=>{var c=
Zb(Wb),d={handle:c,attributes:b,version:b.yc,kc:a};a.canvas&&(a.canvas.Oc=d);Wb[c]=d;("undefined"==typeof b.vc||b.vc)&&bc(d);return c},cc=a=>{X=Wb[a];f.pc=U=X?.kc;return!(a&&!U)},bc=a=>{a||=X;if(!a.Lc){a.Lc=!0;var b=a.kc;Ob(b);Pb(b);2<=a.version&&(b.uc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.uc)b.uc=b.getExtension("EXT_disjoint_timer_query");b.Mc=b.getExtension("WEBGL_multi_draw");Qb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},
dc={},V,X,ec=(a,b,c,d,e,k)=>{a={target:M(a),bc:k,dc:d,ec:(g=event)=>{N.get(d)(e,0,b)&&g.preventDefault()},cc:c};K(a)},fc=(a,b,c,d)=>{Ab||=P(104);return K({target:a,oc:!0,bc:"wheel",dc:d,ec:(e=event)=>{var k=Ab;Gb(k,e,a);B[k+72>>3]=e.deltaX;B[k+80>>3]=e.deltaY;B[k+88>>3]=e.deltaZ;y[k+96>>2]=e.deltaMode;N.get(d)(9,k,b)&&e.preventDefault()},cc:c})},gc=["default","low-power","high-performance"],hc=[null,[],[]],ic=[];function jc(){var a=Qb(U);return a=a.concat(a.map(b=>"GL_"+b))}
var kc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>X.version){V||=1282;return}c=jc().length;break;case 33307:case 33308:if(2>X.version){V||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:V||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V||=1280;r(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:V||=1280;r(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}y[b>>2]=c}else V||=1281},lc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},mc=a=>{var b=lc(a)+1,c=P(b);c&&O(a,c,b);return c},nc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),oc=a=>{a-=5120;return 0==a?qa:1==a?x:2==a?ra:4==a?y:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?z:sa},Y=a=>{var b=U.Ic;if(b){var c=b.jc[a];"number"==typeof c&&(b.jc[a]=c=U.getUniformLocation(b,b.Gc[a]+(0<c?`[${c}]`:"")));return c}V||=1282},qc=a=>{var b=lc(a)+1,c=pc(b);O(a,
c,b);return c};
f.requestFullscreen=function(a,b){function c(){$a=!1;var k=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===k?(d.exitFullscreen=gb,fb&&d.requestPointerLock(),$a=!0,I?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),kb(f.canvas),jb()):kb(d)):(k.parentNode.insertBefore(d,k),k.parentNode.removeChild(k),I?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>
2]&-8388609),kb(f.canvas),jb()):kb(d));f.onFullScreen?.($a);f.onFullscreen?.($a)}fb=a;I=b;"undefined"==typeof fb&&(fb=!0);"undefined"==typeof I&&(I=!1);var d=f.canvas;eb||(eb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};f.requestAnimationFrame=Na;f.setCanvasSize=function(a,b,c){kb(f.canvas,a,b);c||jb()};f.pauseMainLoop=Za;f.resumeMainLoop=function(){H++;var a=Ha,b=Ia,c=F;F=null;Xa(c,0,!1,Qa,!0);Pa(a,b);G()};
f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};f.createContext=function(a,b,c,d){if(b&&f.pc&&a==f.canvas)return f.pc;var e;if(b){var k={antialias:!1,alpha:!1,yc:2};if(d)for(var g in d)k[g]=d[g];if("undefined"!=typeof dc&&(e=ac(a,k)))var l=Wb[e].kc}else l=a.getContext("2d");if(!l)return null;c&&(f.pc=l,b&&cc(e),f.cd=b,bb.forEach(n=>n()),cb());return l};for(var U,rc=0;32>rc;++rc)ic.push(Array(rc));
var Bc={a:()=>{oa("")},nb:()=>{Za();F=null},R:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ba:(a,b,c)=>{a=M(a);if(!a)return-4;a=Db(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},na:La,cb:(a,b,c)=>x.copyWithin(a,b,b+c),ob:()=>performance.now(),Ya:(a,b)=>{function c(d){N.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},bb:()=>{oa("OOM")},W:(a,b,c,d)=>Eb(a,b,c,d,12,"blur"),O:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},X:(a,b,c,d)=>Eb(a,b,c,d,13,"focus"),
fa:(a,b,c,d)=>Fb(a,b,c,d,2,"keydown"),da:(a,b,c,d)=>Fb(a,b,c,d,1,"keypress"),ea:(a,b,c,d)=>Fb(a,b,c,d,3,"keyup"),Za:(a,b,c)=>{a=N.get(a);Xa(a,b,c)},ta:(a,b,c,d)=>Hb(a,b,c,d,5,"mousedown"),ka:(a,b,c,d)=>Hb(a,b,c,d,33,"mouseenter"),ja:(a,b,c,d)=>Hb(a,b,c,d,34,"mouseleave"),oa:(a,b,c,d)=>Hb(a,b,c,d,8,"mousemove"),pa:(a,b,c,d)=>Hb(a,b,c,d,6,"mouseup"),Z:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.hc||document.body.tc||document.body.rc))return-1;a=M(a);if(!a)return-4;
Ib(a,b,c,d,"mozpointerlockchange");Ib(a,b,c,d,"webkitpointerlockchange");Ib(a,b,c,d,"mspointerlockchange");return Ib(a,b,c,d,"pointerlockchange")},Y:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.hc||document.body.tc||document.body.rc))return-1;a=M(a);if(!a)return-4;Jb(a,b,c,d,"mozpointerlockerror");Jb(a,b,c,d,"webkitpointerlockerror");Jb(a,b,c,d,"mspointerlockerror");return Jb(a,b,c,d,"pointerlockerror")},V:(a,b,c,d)=>Kb(a,b,c,d),_:(a,b,c,d)=>Lb(a,b,c,d,25,"touchcancel"),
$:(a,b,c,d)=>Lb(a,b,c,d,23,"touchend"),aa:(a,b,c,d)=>Lb(a,b,c,d,24,"touchmove"),ca:(a,b,c,d)=>Lb(a,b,c,d,22,"touchstart"),U:(a,b,c,d)=>{ec(a,b,c,d,31,"webglcontextlost");return 0},T:(a,b,c,d)=>{ec(a,b,c,d,32,"webglcontextrestored");return 0},ga:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?fc(a,b,c,d):-1:-4,Ia:(a,b)=>{b>>=2;b={alpha:!!y[b],depth:!!y[b+1],stencil:!!y[b+2],antialias:!!y[b+3],premultipliedAlpha:!!y[b+4],preserveDrawingBuffer:!!y[b+5],powerPreference:gc[y[b+6]],failIfMajorPerformanceCaveat:!!y[b+
7],yc:y[b+8],Wc:y[b+9],vc:y[b+10],Jc:y[b+11],Xc:y[b+12],Zc:y[b+13]};a=M(a);return!a||b.Jc?0:ac(a,b)},wa:(a,b)=>{a=Wb[a];b=b?L(x,b):"";b.startsWith("GL_")&&(b=b.substr(3));"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Ob(U);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Pb(U);"WEBGL_multi_draw"==b&&(U.Mc=U.getExtension("WEBGL_multi_draw"));return!!a.kc.getExtension(b)},Aa:a=>cc(a)?0:-5,ha:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var g=z[b>>2],l=z[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=
x[g+n],q=hc[a];0===p||10===p?((1===a?na:r)(L(q,0)),q.length=0):q.push(p)}e+=l}z[d>>2]=e;return 0},k:a=>U.activeTexture(a),M:(a,b)=>{U.attachShader(Q[a],S[b])},b:(a,b)=>{35051==a?U.sc=b:35052==a&&(U.fc=b);U.bindBuffer(a,Sb[b])},h:(a,b)=>{U.bindFramebuffer(a,Tb[b])},Ma:(a,b)=>{U.bindRenderbuffer(a,Ub[b])},j:(a,b)=>{U.bindSampler(a,T[b])},d:(a,b)=>{U.bindTexture(a,R[b])},S:a=>{U.bindVertexArray(Vb[a])},y:(a,b,c,d)=>U.blendColor(a,b,c,d),z:(a,b)=>U.blendEquationSeparate(a,b),A:(a,b,c,d)=>U.blendFuncSeparate(a,
b,c,d),sb:(a,b,c,d,e,k,g,l,n,p)=>U.blitFramebuffer(a,b,c,d,e,k,g,l,n,p),Oa:(a,b,c,d)=>{c&&b?U.bufferData(a,x,d,c,b):U.bufferData(a,b,d)},p:(a,b,c,d)=>{c&&U.bufferSubData(a,b,x,d,c)},H:a=>U.checkFramebufferStatus(a),va:(a,b,c,d)=>U.clearBufferfi(a,b,c,d),E:(a,b,c)=>{U.clearBufferfv(a,b,A,c>>2)},ua:(a,b,c)=>{U.clearBufferiv(a,b,y,c>>2)},l:(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,!!d)},eb:a=>{U.compileShader(S[a])},Fa:(a,b,c,d,e,k,g,l)=>{U.fc||!g?U.compressedTexImage2D(a,b,c,d,e,k,g,l):U.compressedTexImage2D(a,
b,c,d,e,k,x,l,g)},Ha:(a,b,c,d,e,k,g,l,n)=>{U.fc?U.compressedTexImage3D(a,b,c,d,e,k,g,l,n):U.compressedTexImage3D(a,b,c,d,e,k,g,x,n,l)},Ca:()=>{var a=Zb(Q),b=U.createProgram();b.name=a;b.nc=b.lc=b.mc=0;b.qc=1;Q[a]=b;return a},gb:a=>{var b=Zb(S);S[b]=U.createShader(a);return b},sa:a=>U.cullFace(a),hb:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Sb[d];e&&(U.deleteBuffer(e),e.name=0,Sb[d]=null,d==U.sc&&(U.sc=0),d==U.fc&&(U.fc=0))}},m:(a,b)=>{for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=Tb[d];e&&(U.deleteFramebuffer(e),
e.name=0,Tb[d]=null)}},v:a=>{if(a){var b=Q[a];b?(U.deleteProgram(b),b.name=0,Q[a]=null):V||=1281}},P:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Ub[d];e&&(U.deleteRenderbuffer(e),e.name=0,Ub[d]=null)}},Ra:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=T[d];e&&(U.deleteSampler(e),e.name=0,T[d]=null)}},u:a=>{if(a){var b=S[a];b?(U.deleteShader(b),S[a]=null):V||=1281}},Q:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=R[d];e&&(U.deleteTexture(e),e.name=0,R[d]=null)}},Qa:(a,b)=>{for(var c=0;c<
a;c++){var d=y[b+4*c>>2];U.deleteVertexArray(Vb[d]);Vb[d]=null}},r:a=>U.depthFunc(a),s:a=>{U.depthMask(!!a)},e:a=>U.disable(a),qa:a=>{U.disableVertexAttribArray(a)},ub:(a,b,c)=>{U.drawArrays(a,b,c)},vb:(a,b,c,d)=>{U.drawArraysInstanced(a,b,c,d)},G:(a,b)=>{for(var c=ic[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];U.drawBuffers(c)},wb:(a,b,c,d)=>{U.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{U.drawElementsInstanced(a,b,c,d,e)},g:a=>U.enable(a),Hb:a=>{U.enableVertexAttribArray(a)},I:(a,b,c,d)=>{U.framebufferRenderbuffer(a,
b,c,Ub[d])},i:(a,b,c,d,e)=>{U.framebufferTexture2D(a,b,c,R[d],e)},t:(a,b,c,d,e)=>{U.framebufferTextureLayer(a,b,R[c],d,e)},ra:a=>U.frontFace(a),Pa:(a,b)=>{W(a,b,"createBuffer",Sb)},J:(a,b)=>{W(a,b,"createFramebuffer",Tb)},Na:(a,b)=>{W(a,b,"createRenderbuffer",Ub)},Da:(a,b)=>{W(a,b,"createSampler",T)},Ka:(a,b)=>{W(a,b,"createTexture",R)},Ta:(a,b)=>{W(a,b,"createVertexArray",Vb)},ya:(a,b)=>U.getAttribLocation(Q[a],b?L(x,b):""),c:(a,b)=>kc(a,b),za:(a,b,c,d)=>{a=U.getProgramInfoLog(Q[a]);null===a&&(a=
"(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(y[c>>2]=b)},L:(a,b,c)=>{if(c)if(a>=Rb)V||=1281;else if(a=Q[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.nc)for(b=0;b<U.getProgramParameter(a,35718);++b)a.nc=Math.max(a.nc,U.getActiveUniform(a,b).name.length+1);y[c>>2]=a.nc}else if(35722==b){if(!a.lc)for(b=0;b<U.getProgramParameter(a,35721);++b)a.lc=Math.max(a.lc,U.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.lc}else if(35381==b){if(!a.mc)for(b=
0;b<U.getProgramParameter(a,35382);++b)a.mc=Math.max(a.mc,U.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.mc}else y[c>>2]=U.getProgramParameter(a,b);else V||=1281},db:(a,b,c,d)=>{a=U.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(y[c>>2]=b)},ia:(a,b,c)=>{c?35716==b?(a=U.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(S[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=U.getShaderParameter(S[a],b):V||=1281},Ua:(a,b)=>
{if(2>X.version)return V||=1282,0;var c=Xb[a];if(c)return 0>b||b>=c.length?(V||=1281,0):c[b];switch(a){case 7939:return c=jc().map(mc),c=Xb[a]=c,0>b||b>=c.length?(V||=1281,0):c[b];default:return V||=1280,0}},o:(a,b)=>{b=b?L(x,b):"";if(a=Q[a]){var c=a,d=c.jc,e=c.Hc,k;if(!d)for(c.jc=d={},c.Gc={},k=0;k<U.getProgramParameter(c,35718);++k){var g=U.getActiveUniform(c,k);var l=g.name;g=g.size;var n=nc(l);n=0<n?l.slice(0,n):l;var p=c.qc;c.qc+=g;e[n]=[g,p];for(l=0;l<g;++l)d[p]=l,c.Gc[p++]=n}c=a.jc;d=0;e=b;
k=nc(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Hc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else V||=1281;return-1},rb:(a,b,c)=>{for(var d=ic[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];U.invalidateFramebuffer(a,d)},Ba:a=>{a=Q[a];U.linkProgram(a);a.jc=0;a.Hc={}},Sa:(a,b)=>{3317==a&&(Yb=b);U.pixelStorei(a,b)},D:(a,b)=>U.polygonOffset(a,b),tb:a=>U.readBuffer(a),La:(a,b,c,d,e)=>U.renderbufferStorageMultisample(a,b,c,d,e),N:(a,b,c)=>{U.samplerParameterf(T[a],b,c)},f:(a,
b,c)=>{U.samplerParameteri(T[a],b,c)},xa:(a,b,c,d)=>U.scissor(a,b,c,d),fb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var g=(g=z[c+4*k>>2])?L(x,g,d?z[d+4*k>>2]:void 0):"";e+=g}U.shaderSource(S[a],e)},jb:(a,b,c)=>U.stencilFunc(a,b,c),C:(a,b,c,d)=>U.stencilFuncSeparate(a,b,c,d),q:a=>U.stencilMask(a),ib:(a,b,c)=>U.stencilOp(a,b,c),B:(a,b,c,d)=>U.stencilOpSeparate(a,b,c,d),Ea:(a,b,c,d,e,k,g,l,n)=>{if(U.fc)U.texImage2D(a,b,c,d,e,k,g,l,n);else if(n){var p=oc(l);U.texImage2D(a,b,c,d,e,k,g,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else U.texImage2D(a,
b,c,d,e,k,g,l,null)},Ga:(a,b,c,d,e,k,g,l,n,p)=>{if(U.fc)U.texImage3D(a,b,c,d,e,k,g,l,n,p);else if(p){var q=oc(n);U.texImage3D(a,b,c,d,e,k,g,l,n,q,p>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else U.texImage3D(a,b,c,d,e,k,g,l,n,null)},Ja:(a,b,c)=>U.texParameteri(a,b,c),pb:(a,b,c,d,e,k,g,l,n)=>{if(U.fc)U.texSubImage2D(a,b,c,d,e,k,g,l,n);else if(n){var p=oc(l);U.texSubImage2D(a,b,c,d,e,k,g,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}if(n){p=oc(l);var q=Yb;q=k*(e*({5:3,6:4,8:2,29502:3,29504:4,26917:2,
26918:2,29846:3,29847:4}[g-6402]||1)*p.BYTES_PER_ELEMENT+q-1&-q);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+q>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;U.texSubImage2D(a,b,c,d,e,k,g,l,n)},qb:(a,b,c,d,e,k,g,l,n,p,q)=>{if(U.fc)U.texSubImage3D(a,b,c,d,e,k,g,l,n,p,q);else if(q){var t=oc(p);U.texSubImage3D(a,b,c,d,e,k,g,l,n,p,t,q>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else U.texSubImage3D(a,b,c,d,e,k,g,l,n,p,null)},Gb:(a,b,c)=>{b&&U.uniform1fv(Y(a),A,c>>2,b)},K:(a,b)=>{U.uniform1i(Y(a),
b)},Cb:(a,b,c)=>{b&&U.uniform1iv(Y(a),y,c>>2,b)},Fb:(a,b,c)=>{b&&U.uniform2fv(Y(a),A,c>>2,2*b)},Bb:(a,b,c)=>{b&&U.uniform2iv(Y(a),y,c>>2,2*b)},Eb:(a,b,c)=>{b&&U.uniform3fv(Y(a),A,c>>2,3*b)},Ab:(a,b,c)=>{b&&U.uniform3iv(Y(a),y,c>>2,3*b)},Db:(a,b,c)=>{b&&U.uniform4fv(Y(a),A,c>>2,4*b)},zb:(a,b,c)=>{b&&U.uniform4iv(Y(a),y,c>>2,4*b)},yb:(a,b,c,d)=>{b&&U.uniformMatrix4fv(Y(a),!!c,A,d>>2,16*b)},n:a=>{a=Q[a];U.useProgram(a);U.Ic=a},Ib:(a,b)=>{U.vertexAttribDivisor(a,b)},Jb:(a,b,c,d,e,k)=>{U.vertexAttribPointer(a,
b,c,!!d,e,k)},F:(a,b,c,d)=>U.viewport(a,b,c,d),ab:function(){f.Ac=a=>{0!=sc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Ac)},$a:function(){f.Fc=a=>{const b=a.clipboardData.getData("text");nb(()=>{const c=qc(b);tc(c)})};window.addEventListener("paste",f.Fc)},_a:function(a){f.$c=[];a=a?L(x,a):"";a=document.getElementById(a);f.Bc=b=>{b.stopPropagation();b.preventDefault()};f.Cc=b=>{b.stopPropagation();b.preventDefault()};f.Dc=b=>{b.stopPropagation();b.preventDefault()};
f.Ec=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.ad=c;uc(c.length);for(let e=0;e<c.length;e++)nb(()=>{const k=qc(c[e].name);vc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);wc(b.clientX,b.clientY,d)};a.addEventListener("dragenter",f.Bc,!1);a.addEventListener("dragleave",f.Cc,!1);a.addEventListener("dragover",f.Dc,!1);a.addEventListener("drop",f.Ec,!1)},Wa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},
Xa:function(){document.exitPointerLock&&document.exitPointerLock()},Kb:function(a){a=a?L(x,a):"";f.ic=document.getElementById(a);f.ic||console.log("sokol_app.h: invalid target:"+a);f.ic.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},mb:function(){window.removeEventListener("beforeunload",f.Ac)},lb:function(){window.removeEventListener("paste",f.Fc)},kb:function(a){a=a?L(x,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",f.Bc);a.removeEventListener("dragleave",
f.Cc);a.removeEventListener("dragover",f.Dc);a.removeEventListener("drop",f.Ec)},w:function(){f.ic&&f.ic.requestPointerLock&&f.ic.requestPointerLock()},Va:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(x.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},x:function(a,b,c,d,e,k){b=b?L(x,
b):"";const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const l=0<d;l&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!l){const n=new Uint8Array(g.response),p=n.length;p<=k?(x.set(n,e),xc(a,d,p)):yc(a)}else zc(a,g.status)};g.send()},ma:function(a,b){b=b?L(x,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==
c.status){const d=c.getResponseHeader("Content-Length");Ac(a,d)}else zc(a,c.status)};c.send()},la:function(a,b){b=b?L(x,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;pa=Z.Lb;c=pa.buffer;f.HEAP8=qa=new Int8Array(c);f.HEAP16=ra=new Int16Array(c);f.HEAPU8=x=new Uint8Array(c);f.HEAPU16=sa=new Uint16Array(c);f.HEAP32=y=new Int32Array(c);f.HEAPU32=z=new Uint32Array(c);f.HEAPF32=A=
new Float32Array(c);f.HEAPF64=B=new Float64Array(c);N=Z.Ob;ua.unshift(Z.Mb);C--;f.monitorRunDependencies?.(C);0==C&&(null!==ya&&(clearInterval(ya),ya=null),D&&(c=D,D=null,c()));return Z}var b={a:Bc};C++;f.monitorRunDependencies?.(C);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return r(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ea(b,function(c){a(c.instance)});return{}}(),P=a=>(P=Z.Nb)(a),tc=f.__sapp_emsc_onpaste=a=>(tc=f.__sapp_emsc_onpaste=Z.Pb)(a),sc=f.__sapp_html5_get_ask_leave_site=
()=>(sc=f.__sapp_html5_get_ask_leave_site=Z.Qb)(),uc=f.__sapp_emsc_begin_drop=a=>(uc=f.__sapp_emsc_begin_drop=Z.Rb)(a),vc=f.__sapp_emsc_drop=(a,b)=>(vc=f.__sapp_emsc_drop=Z.Sb)(a,b),wc=f.__sapp_emsc_end_drop=(a,b,c)=>(wc=f.__sapp_emsc_end_drop=Z.Tb)(a,b,c);f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,g,l)=>(f.__sapp_emsc_invoke_fetch_cb=Z.Ub)(a,b,c,d,e,k,g,l);
var Cc=f._main=(a,b)=>(Cc=f._main=Z.Vb)(a,b),Ac=f.__sfetch_emsc_head_response=(a,b)=>(Ac=f.__sfetch_emsc_head_response=Z.Wb)(a,b),xc=f.__sfetch_emsc_get_response=(a,b,c)=>(xc=f.__sfetch_emsc_get_response=Z.Xb)(a,b,c),zc=f.__sfetch_emsc_failed_http_status=(a,b)=>(zc=f.__sfetch_emsc_failed_http_status=Z.Yb)(a,b),yc=f.__sfetch_emsc_failed_buffer_too_small=a=>(yc=f.__sfetch_emsc_failed_buffer_too_small=Z.Zb)(a),lb=()=>(lb=Z._b)(),mb=a=>(mb=Z.$b)(a),pc=a=>(pc=Z.ac)(a);f.___start_em_js=166184;
f.___stop_em_js=173398;var Dc;D=function Ec(){Dc||Fc();Dc||(D=Ec)};function Gc(a=[]){var b=Cc;a.unshift(ca);var c=a.length,d=pc(4*(c+1)),e=d;a.forEach(g=>{z[e>>2]=qc(g);e+=4});z[e>>2]=0;try{var k=b(c,d);Ya(k)}catch(g){Wa(g)}}
function Fc(){var a=ba;function b(){if(!Dc&&(Dc=!0,f.calledRun=!0,!v)){Fa(ua);Fa(va);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Hc&&Gc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();wa.unshift(c)}Fa(wa)}}if(!(0<C)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)xa();Fa(ta);0<C||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Hc=!0;f.noInitialRun&&(Hc=!1);Fc();
